local data={
	save=2,
	savedata={
		koins=1333333333333333337,
		main={
			upgrades={dunk={max=17, current=20},
			defense={max=15, current=20},
			steal={max=13, current=20},
			jump={max=15, current=20},
			freethrow={max=11, current=20},
			shotcontest={max=18, current=20},
			["2pointer"]={max=20, current=20},
			["3pointer"]={max=11, current=20},
			handles={max=15, current=20},
			layup={max=12, current=20},
			postscorer={max=9, current=20},
			ballspeed={max=9, current=20},
			speed={max=11, current=20},
			passing={max=15, current=20},
			movingshot={max=13, current=20},
			strength={max=7, current=20}},
			park_onanimations={},
			rb7_celebrations={},
			jumpshots={"Starter Jumpshot 1", "Starter Jumpshot 2", "Starter Jumpshot 3"},
			prestige=3,
			pants={"Grey Joggers"},
			level=1377,
			layups={"Starter Layup 1", "Starter Layup 2"},
			shoes={"RB Generics"},
			park="westlake",
			dunks={"Big Slam"},
			currentexp=0,
			hats={"Nothing"},
			customjumpshots={},
			park_celebrations={},
			position="SG",
			playstyle="Splasher",
			skills = {
                              ["2pointer"] = 59,
                              ["3pointer"] = 59,
                              ballspeed = 59,
                              defense = 59,
                              dunk = 59,
                              freethrow = 59,
                              handles = 59,
                              jump = 59,
                              layup = 59,
                              movingshot = 59,
                              passing = 59,
                              postscorer = 59,
                              shotcontest = 59,
                              speed = 59,
                              steal = 59,
                              strength = 59,
			},
			maxexp=109999990,
			shirts={"Plain White Shirt"}
		},
		appearance={
			dunk="698187843", park_onanimations={},
			rb7_celebrations={},
			hat2={meshid="", textureid="", name="None", pos={y=0, z=0}},
			layup={name="Starter Layup 1", idr="696678129", idl="696677707"},
			shirt="225684460",
			weight=185,
			pants="945117814",
			shoes={name="RB Generics", shoetype="MidShoe", idr="945506326", idl="945506326"},
			hat={meshid="", textureid="", name="None", pos={y=0, z=0}},
			skincolor="Cashmere",
			gender="Male",
			park_celebrations={},
			haircolor="Black",
			height=6.1,
			shothand="R",
			jumpshot={name="Starter Jumpshot 1", shot="697217666", jump="697208867"},
			hair={meshid="", pos={y=0, z=0},name="Bald",size={y=0, x=0, z=0}}
		},
		upgrading=1
	},
	maindata={
		friends={},
		name=game.Players.LocalPlayer.Name,
		park="",
		id=game.Players.LocalPlayer.userId,
		follow="Anyone",
		league=0,
		gym=0
	}
}

game.ReplicatedStorage.tp:FireServer(data)