local hub = game.CoreGui.skryptec_hub
local apocbottom = hub.ApocBottomFrame
local apoctypee = apocbottom.ApocType.Text

Player = apoctypee

game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slotbackpack, 4016)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slotprimary, 1035)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot1, 9013)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot2, 9010)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot4, 50)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot5, 50)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot6, 50)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot7, 50)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot8, 50)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot9, 50)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot10, 50)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot11, 50)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot12, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot13, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot14, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot15, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot16, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot17, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot18, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot19, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot20, 11)
wait(.1)