-- ring mesh: http://www.roblox.com/asset/?id=3270017

robot = Instance.new("Model")
robot.Parent = game.Workspace

n = Instance.new("Part")
n.Anchored = false
n.Locked = true
n.CanCollide = true
n.formFactor = "Symmetric"
n.Shape = "Ball"
n.Size = Vector3.new(2,2,2)
n.BrickColor = BrickColor.new("Really black")
n.Name = "Wheel"
n.Parent = robot
n.CFrame = CFrame.new(20,2,20)
m = Instance.new("SpecialMesh")
m.MeshType = "FileMesh"
m.Scale = Vector3.new(2,2,2)
m.MeshId = "http://www.roblox.com/asset/?id=3270017"
m.Parent = n
g = Instance.new("BodyGyro")
g.maxTorque = Vector3.new(math.huge,math.huge,math.huge)
g.Parent = n
b = Instance.new("BodyVelocity")
b.maxForce = Vector3.new(math.huge,math.huge,math.huge)
b.velocity = Vector3.new(0,2,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(2,2,2)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "FileMesh"
m.Scale = Vector3.new(1.75,1.75,1.5)
m.MeshId = "http://www.roblox.com/asset/?id=3270017"
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

--WheelStart 

wheel = Instance.new("Model")
wheel.Parent = robot

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(2,2,2)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = wheel
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.05,0.9,0.05)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(2,2,2)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = wheel
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.05,0.9,0.05)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,3.14/2)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(2,2,2)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = wheel
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.05,0.9,0.05)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,3.14/2/2)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(2,2,2)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = wheel
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.05,0.9,0.05)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,-3.14/2/2)

--EndBikeWheelBlaBlaBla

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(2,2,2)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "FileMesh"
m.Scale = Vector3.new(0.15,0.15,1.5)
m.MeshId = "http://www.roblox.com/asset/?id=3270017"
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(2,2,2)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.05,0.5,0.05)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(3.14/2,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.2,1,0.2)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-0.4,0.4) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.2,1,0.2)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-0.4,-0.4) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Sphere"
m.Scale = Vector3.new(0.2,0.2,0.2)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-0.85,-0.4) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.2,0.2,0.2)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-0.8,-0.56) * CFrame.fromEulerAnglesXYZ(0.2,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Sphere"
m.Scale = Vector3.new(0.2,0.2,0.2)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-0.85,0.4) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.2,0.2,0.2)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-0.8,0.56) * CFrame.fromEulerAnglesXYZ(-0.2,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Sphere"
m.Scale = Vector3.new(0.2,0.2,0.2)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-0.728,0.72) * CFrame.fromEulerAnglesXYZ(-0.4,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Sphere"
m.Scale = Vector3.new(0.2,0.2,0.2)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-0.728,-0.72) * CFrame.fromEulerAnglesXYZ(0.4,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.18,0.4,0.18)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-0.8,-0.8) * CFrame.fromEulerAnglesXYZ(0.5,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.18,0.4,0.18)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-0.8,0.8) * CFrame.fromEulerAnglesXYZ(-0.5,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.18,0.6,0.18)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,0,-1.225) * CFrame.fromEulerAnglesXYZ(math.pi/2,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.18,2.5,0.18)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-2,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.5,2.25,0.5)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-2.5,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Sphere"
m.Scale = Vector3.new(0.75,2,0.75)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-2.85,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

-- [[ * HEAD * ]] ---

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Sphere"
m.Scale = Vector3.new(1.2,1.2,1.2)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-4.125,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Really black")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Sphere"
m.Scale = Vector3.new(1.2,0.6,1.2)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0.1,-4.145,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

-- [[ * ARM A * ]] --

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.5,2.25/2,0.5)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-3,0.5) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.475,2.3/2,0.475)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0.625,-2,-0.1) * CFrame.fromEulerAnglesXYZ(0.2,0.2,0.2)

-- [[ * ARM B * ]] --

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.5,2.25/2,0.5)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0,-3,-0.5) * CFrame.fromEulerAnglesXYZ(0,0,0)

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.475,2.3/2,0.475)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(0.625,-2,0.1) * CFrame.fromEulerAnglesXYZ(-0.2,-0.2,0.2)

--[[ Minigun

p = Instance.new("Part")
p.Anchored = false
p.Locked = true
p.CanCollide = true
p.formFactor = "Symmetric"
p.Shape = "Ball"
p.Size = Vector3.new(1,1,1)
p.BrickColor = BrickColor.new("Mid gray")
p.Name = "Wheel"
p.Parent = robot
p.CFrame = CFrame.new(0,2,0)
m = Instance.new("SpecialMesh")
m.MeshType = "Head"
m.Scale = Vector3.new(0.475,2.3/2,0.475)
m.Parent = p
w = Instance.new("Weld")
w.Parent = p
w.Part0 = p
w.Part1 = n
w.C0 = CFrame.new(1.5,-1.6,0.185) * CFrame.fromEulerAnglesXYZ(0.1,0.1,0.6)

]]

while true do wait()
for i,v in pairs(wheel:GetChildren()) do
if v:findFirstChild("Weld") ~= nil then
v.Weld.C0 = v.Weld.C0 * CFrame.Angles(0,0,-math.pi/20)
print("WeldFound")
else
print("NoWeld")
end
end
end
