luac'getglobal game'
luac'getfield -1 GetService'
luac'pushvalue -2'
luac'pushstring Players'
luac'pcall 2 1 0'
luac'getfield -1 LocalPlayer'
luac'getfield -1 Backpack'
luac'getglobal Instance'
luac'getfield -1 new'
luac'pushstring HopperBin'
luac'pushvalue -4'
luac'pcall 2 1 0'
luac'pushnumber 1'
luac'setfield -2 BinType'
luac'emptystack'
luac'getglobal game'
luac'getfield -1 GetService'
luac'pushvalue -2'
luac'pushstring Players'
luac'pcall 2 1 0'
luac'getfield -1 LocalPlayer'
luac'getfield -1 Backpack'
luac'getglobal Instance'
luac'getfield -1 new'
luac'pushstring HopperBin'
luac'pushvalue -4'
luac'pcall 2 1 0'
luac'pushnumber 2'
luac'setfield -2 BinType'
luac'emptystack'
luac'getglobal game'
luac'getfield -1 GetService'
luac'pushvalue -2'
luac'pushstring Players'
luac'pcall 2 1 0'
luac'getfield -1 LocalPlayer'
luac'getfield -1 Backpack'
luac'getglobal Instance'
luac'getfield -1 new'
luac'pushstring HopperBin'
luac'pushvalue -4'
luac'pcall 2 1 0'
luac'pushnumber 3'
luac'setfield -2 BinType'
luac'emptystack'
luac'getglobal game'
luac'getfield -1 GetService'
luac'pushvalue -2'
luac'pushstring Players'
luac'pcall 2 1 0'
luac'getfield -1 LocalPlayer'
luac'getfield -1 Backpack'
luac'getglobal Instance'
luac'getfield -1 new'
luac'pushstring HopperBin'
luac'pushvalue -4'
luac'pcall 2 1 0'
luac'pushnumber 4'
luac'setfield -2 BinType'
luac'emptystack'