local brick = Instance.new("Part")
brick.BrickColor = BrickColor.new("Brown")
brick.Parent = game.Workspace.acb227 
brick.Name = "Right Arm" 
brick.Size = Vector3.new(2, 2, 2) 
brick.Position = Vector3.new(-5, 1, 17) 
brick.Anchored = false 
brick.CanCollide = true 
brick.Locked = true 
brick.Material = "Plastic" 
brick.Shape = "Cylinder"
brick.TopSurface = "Smooth"
brick.BottomSurface = "Smooth"
brick.LeftSurface = "Hinge"

--h = Instance.new("BlockMesh") 
--h.Scale = Vector3.new(1, 1, 1) 
--h.Offset = Vector3.new(0, 0, 0) 
--h.Parent = brick

local brick = Instance.new("Part")
brick.BrickColor = BrickColor.new("Brown")
brick.Parent = game.Workspace.acb227 
brick.Name = "Right Arm" 
brick.Size = Vector3.new(2, 2, 2) 
brick.Position = Vector3.new(-5, 1, 0) 
brick.Anchored = false 
brick.CanCollide = true 
brick.Locked = true 
brick.Material = "Plastic" 
brick.Shape = "Cylinder"
brick.TopSurface = "Smooth"
brick.BottomSurface = "Smooth"
brick.LeftSurface = "Hinge"

--h = Instance.new("BlockMesh") 
--h.Scale = Vector3.new(1, 1, 1) 
--h.Offset = Vector3.new(0, 0, 0) 
--h.Parent = brick

local brick = Instance.new("Part")
brick.BrickColor = BrickColor.new("Brown")
brick.Parent = game.Workspace.acb227 
brick.Name = "Right Arm" 
brick.Size = Vector3.new(2, 2, 2) 
brick.Position = Vector3.new(-17, 1, 17) 
brick.Anchored = false 
brick.CanCollide = true 
brick.Locked = true 
brick.Material = "Plastic" 
brick.Shape = "Cylinder"
brick.TopSurface = "Smooth"
brick.BottomSurface = "Smooth"
brick.RightSurface = "Hinge"
---------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor = BrickColor.new("Brown")
brick.Parent = game.Workspace.acb227 
brick.Name = "Right Arm" 
brick.Size = Vector3.new(2, 2, 2) 
brick.Position = Vector3.new(-17, 1, 0) 
brick.Anchored = false 
brick.CanCollide = true 
brick.Locked = true 
brick.Material = "Plastic" 
brick.Shape = "Cylinder"
brick.TopSurface = "Smooth"
brick.BottomSurface = "Smooth"
brick.RightSurface = "Hinge"
-------------------------------------------------------
local brick1 = Instance.new("Part")
brick1.BrickColor = BrickColor.new("Brown")
brick1.Parent = game.Workspace.acb227 
brick1.Name = "Right Arm" 
brick1.Size = Vector3.new(10, 1, 19) 
brick1.Position = Vector3.new(-11, 2.5, 8.5) 
brick1.Anchored = false 
brick1.CanCollide = true 
brick1.Locked = true 
brick1.TopSurface = "Weld"
brick1.BottomSurface = "Smooth"
--------------------------------------------------
local brick = Instance.new("VehicleSeat")
brick2.BrickColor = BrickColor.new("Brown")
brick2.Parent = game.Workspace.acb227 
brick2.Name = "Right Arm" 
brick2.Size = Vector3.new(2, 1, 2) 
brick2.Position = Vector3.new(-11, 3, 8.5) 
brick2.CanCollide = true 
brick2.Locked = true 
brick2.TopSurface = "Smooth"
brick2.BottomSurface = "Weld"