local Model = Workspace.DarkShadow6
local CharacterMesh = Instance.new("CharacterMesh")
CharacterMesh.Name = "ROBLOX 2.0 Torso"
CharacterMesh.BodyPart = "Torso"
CharacterMesh.MeshId = "27111894"
CharacterMesh.Parent = Model
local CharacterMesh = Instance.new("CharacterMesh")
CharacterMesh.Name = "ROBLOX 2.0 Torso"
CharacterMesh.BodyPart = "Torso"
CharacterMesh.MeshId = "27111894"
CharacterMesh.Parent = Model
local CharacterMesh = Instance.new("CharacterMesh")
CharacterMesh.Name = "ROBLOX 2.0 Left Arm"
CharacterMesh.BodyPart = "LeftArm"
CharacterMesh.MeshId = "27111419"
CharacterMesh.Parent = Model
local CharacterMesh = Instance.new("CharacterMesh")
CharacterMesh.Name = "ROBLOX 2.0 Right Arm"
CharacterMesh.BodyPart = "RightArm"
CharacterMesh.MeshId = "27111864"
CharacterMesh.Parent = Model
local CharacterMesh = Instance.new("CharacterMesh")
CharacterMesh.Name = "ROBLOX 2.0 Left Leg"
CharacterMesh.BodyPart = "LeftLeg"
CharacterMesh.MeshId = "27111857"
CharacterMesh.Parent = Model
local CharacterMesh = Instance.new("CharacterMesh")
CharacterMesh.Name = "ROBLOX 2.0 Right Leg"
CharacterMesh.BodyPart = "RightLeg"
CharacterMesh.MeshId = "27111882"
CharacterMesh.Parent = Model