pcall(function() Workspace.Spawn:Remove() end) 
local spread = 10 
local m = Instance.new("Model",Workspace) 
m.Name = "Spawn" 
m.Parent = Workspace 
for ii = 1, 1 do 
for i = 1, 44 do 
p = Instance.new("Part") 
p.Name = "Part"..i 
p.BrickColor=BrickColor.new("Magenta") 
p.Anchored = true 
p.Parent = m 
p.Size = Vector3.new(10,1,4) 
p.CFrame = CFrame.fromEulerAnglesXYZ(0,math.rad(i/2),0) * CFrame.new(0,2,i*ii) 
BM=Instance.new("BlockMesh",p) 
BM.Scale=Vector3.new(1,1,1) 
p = Instance.new("Part") 
p.Name = "Part"..i 
p.BrickColor=BrickColor.new("Magenta") 
p.Anchored = true 
p.Parent = m 
p.Size = Vector3.new(10,1,4) 
p.CFrame = CFrame.fromEulerAnglesXYZ(0,math.rad(i/-2),0) * CFrame.new(0,2,i*ii) 
BM=Instance.new("BlockMesh",p) 
BM.Scale=Vector3.new(1,1,1) 
p = Instance.new("Part") 
p.Name = "Part"..i 
p.BrickColor=BrickColor.new("Magenta") 
p.Anchored = true 
p.Parent = m 
p.Size = Vector3.new(10,1,4) 
p.CFrame = CFrame.fromEulerAnglesXYZ(0,math.rad(-i*2),0) * CFrame.new(0,2,i*ii) 
BM=Instance.new("BlockMesh",p) 
BM.Scale=Vector3.new(1,1,1) 
p = Instance.new("Part") 
p.Name = "Part"..i 
p.BrickColor=BrickColor.new("Magenta") 
p.Anchored = true 
p.Parent = m 
p.Size = Vector3.new(10,1,4) 
p.CFrame = CFrame.fromEulerAnglesXYZ(0,math.rad(-i*-2),0) * CFrame.new(0,2,i*ii) 
BM=Instance.new("BlockMesh",p) 
BM.Scale=Vector3.new(1,1,1) 
p = Instance.new("Part") 
end 
end 
p = Instance.new("SpawnLocation") 
p.Name = "Part" 
p.BrickColor=BrickColor.new("Really red") 
d=Instance.new("Decal",p) 
d.Texture="http://www.roblox.com/asset/?id=13038247" 
d.Face="Top" 
p.Anchored = true 
p.Parent = m 
p.Size = Vector3.new(21,1,30) 
p.CFrame = CFrame.new(0,2,-16) 
p.CFrame = p.CFrame * CFrame.Angles(0,math.pi,0) 
BM=Instance.new("BlockMesh",p) 
BM.Scale=Vector3.new(1,1,1) 
p = Instance.new("Part") 
p.Name = "Part" 
p.BrickColor=BrickColor.new("Really black") 
p.CanCollide=false 
p.Anchored = true 
p.Parent = m 
p.formFactor="Custom" 
p.Size = Vector3.new(8,0.2,8) 
p.CFrame = CFrame.new(4.25,2.6,-21) 
CM=Instance.new("CylinderMesh",p) 
CM.Scale=Vector3.new(1,1,1) 
p = Instance.new("Part") 
p.Name = "Part" 
p.BrickColor=BrickColor.new("Really black") 
p.CanCollide=false 
p.Anchored = true 
p.Parent = m 
p.formFactor="Custom" 
p.Size = Vector3.new(8,0.2,8) 
p.CFrame = CFrame.new(-4.25,2.6,-21) 
CM=Instance.new("CylinderMesh",p) 
CM.Scale=Vector3.new(1,1,1) 
