-- If glitched, drop all your items and pick them up again
Player = "cProximity" -- Name here

wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slotbackpack, 16)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slotprimary, 1016)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slotsecondary, 2011)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot1, 64)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot2, 64)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot3, 55)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot4, 55)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot5, 9005)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot6, 9013)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot7, 9010)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot8, 9007)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot9, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot10, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot11, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot12, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot13, 5011)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot14, 6011)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot15, 7009)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot16, 8009)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot17, 64)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot18, 64)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot19, 64)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot20, 3014)
wait(.1)
