------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Reddish brown")
brick.Parent = game.Workspace 
brick.Name = "Dogy" 
brick.Size = Vector3.new(1, 6, 10) 
brick.Position = Vector3.new(20, 99, 50) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Reddish brown")
brick.Parent = game.Workspace 
brick.Name = "Dogy" 
brick.Size = Vector3.new(1, 6, 10) 
brick.Position = Vector3.new(10, 99, 50) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Reddish brown")
brick.Parent = game.Workspace 
brick.Name = "Dogy" 
brick.Size = Vector3.new(9, 6, 1) 
brick.Position = Vector3.new(15, 99, 54.5) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Reddish brown")
brick.Parent = game.Workspace 
brick.Name = "Dogy" 
brick.Size = Vector3.new(3, 6, 1) 
brick.Position = Vector3.new(24, 99, 45.5) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Reddish brown")
brick.Parent = game.Workspace 
brick.Name = "Dogy" 
brick.Size = Vector3.new(3, 6, 1) 
brick.Position = Vector3.new(12, 99, 45.5) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Bright red")
brick.Parent = game.Workspace 
brick.Name = "Dogy" 
brick.Size = Vector3.new(10, 1, 10) 
brick.Position = Vector3.new(10, 99, 50) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)