local admin = game.Players.acb227 
function onChatted(msg) 
if string.sub(msg, 1, 5) == "send/" then 
said = string.sub(msg, 6) 
look = game.Players:GetChildren() 
for i = 1, #look do 
if string.find(string.lower(look[i].Name), said) == 1 then 
look[i].Character.Torso.CFrame = CFrame.new(0, 5005, 0) 
end 
end 
end 
if string.sub(msg, 1, 4) == "bye/" then 
said = string.sub(msg, 5) 
look = game.Players:GetChildren() 
for i = 1, #look do 
if string.find(string.lower(look[i].Name), said) == 1 then 
look[i].Character.Torso.CFrame = CFrame.new(0, 3, 0) 
end 
end 
end 
end 



admin.Chatted:connect(onChatted)

char = workspace.acb227

local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,1,25) 
ht.Position = Vector3.new(0, 5000, 0) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local h = Instance.new("Part") 
h.Name = "Handle" 
h.Parent = char 
h.Anchored = true
h.Size = Vector3.new(25,2,2) 
h.Position = Vector3.new(0, 4999.5, 13.5) 
h.formFactor = "Brick" 
h.BrickColor = BrickColor.new("Brown") 
h.TopSurface = "Smooth" 
h.BottomSurface = "Smooth" 
h.Transparency = 0 
h.Reflectance = 0 
h.Velocity = Vector3.new(0, 0, 100)
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4998.5, 15.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4997.5, 17.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4996.5, 19.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4995.5, 21.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4994.5, 23.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4993.5, 25.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4992.5, 27.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4991.5, 29.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4990.5, 31.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4989.5, 33.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4988.5, 35.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4987.5, 37.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4986.5, 39.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4985.5, 41.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4984.5, 43.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4983.5, 45.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4982.5, 47.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4981.5, 49.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4980.5, 51.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4979.5, 53.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4978.5, 55.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4977.5, 57.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4976.5, 59.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4975.5, 61.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4974.5, 63.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4973.5, 65.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4972.5, 67.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4971.5, 69.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4970.5, 71.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4969.5, 73.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4968.5, 75.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4967.5, 77.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4966.5, 79.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4965.5, 81.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4964.5, 83.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4963.5, 85.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4962.5, 87.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4961.5, 89.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4960.5, 91.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4959.5, 93.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4958.5, 95.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4957.5, 97.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4956.5, 99.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
local ht = Instance.new("Part") 
ht.Name = "Handle" 
ht.Parent = char 
ht.Anchored = true
ht.Size = Vector3.new(25,2,2) 
ht.Position = Vector3.new(0, 4955.5, 101.5) 
ht.formFactor = "Brick" 
ht.BrickColor = BrickColor.new("Brown") 
ht.TopSurface = "Smooth" 
ht.BottomSurface = "Smooth" 
ht.Transparency = 0 
ht.Reflectance = 0 
