
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 52) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 50) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 48) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 46) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 44) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 42) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 40) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 38) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 36) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 34) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 32) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 30) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 28) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 26) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 24) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(26, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 54) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 56) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 58) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 60) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 62) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 64) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 66) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 68) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 70) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 72) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 74) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(27, 99, 76) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(24, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(22, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(20, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(18, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(16, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(14, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(12, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(10, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(8, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(6, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(4, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(2, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(0, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-2, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-4, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-6, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-8, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-10, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-12, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-14, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-16, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-18, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-20, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-22, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-24, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-26, 99, 23) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 24) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 26) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 28) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 30) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 32) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 34) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 36) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 38) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 40) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 42) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 44) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 46) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 48) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 50) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 52) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 54) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 56) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 58) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 60) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 62) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 64) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 66) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 68) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 70) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 72) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 74) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-27, 99, 76) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-26, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-24, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-22, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-20, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-18, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-16, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-14, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-12, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-10, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-8, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-6, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-4, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(-2, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(0, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(2, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(4, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(6, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(8, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(10, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(12, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(14, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(16, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(18, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(20, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(22, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(24, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 2, 1) 
brick.Position = Vector3.new(26, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 1, 55) 
brick.Position = Vector3.new(27, 99, 49.5) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(1, 1, 55) 
brick.Position = Vector3.new(-27, 99, 50) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(53, 1, 1) 
brick.Position = Vector3.new(0, 99, 77) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)
------------------------------------------------------
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Mid grey")
brick.Parent = game.Workspace.acb227 
brick.Name = "Fence" 
brick.Size = Vector3.new(53, 1, 1) 
brick.Position = Vector3.new(0, 99, 20.5) 
brick.Anchored = true 
brick.CanCollide = true 
brick.Locked = true 
brick.Transparency = 0 
brick.Reflectance = 0 
brick.FormFactor = (2)