--------[[body fire lego]]---------------------
f=Instance.new('Fire')
f.Size=8
f.Heat=7
f.Color = BrickColor.new("Bright blue").Color;
f.SecondaryColor = BrickColor.new("Bright blue").Color;
f.Parent=game.Players.LocalPlayer.Character.Torso;
f=Instance.new('Fire')
f.Size=8
f.Heat=7
f.Color = BrickColor.new("Really black").Color;
f.SecondaryColor = BrickColor.new("Really black").Color;
f.Parent=game.Players.LocalPlayer.Character["Right Arm"]
f=Instance.new('Fire')
f.Size=8
f.Heat=7
f.Color = BrickColor.new("Really red").Color;
f.SecondaryColor = BrickColor.new("Really red").Color;
f.Parent=game.Players.LocalPlayer.Character["Left Arm"]
f=Instance.new('Fire')
f.Size=8
f.Heat=7
f.Color = BrickColor.new("Bright violet").Color;
f.SecondaryColor = BrickColor.new("Bright violet").Color;
f.Parent=game.Players.LocalPlayer.Character["Head"]
f=Instance.new('Fire')
f.Size=8
f.Heat=7
f.Color = BrickColor.new("Institutional white").Color;
f.SecondaryColor = BrickColor.new("Institutional white").Color;
f.Parent=game.Players.LocalPlayer.Character["Right Leg"]
f=Instance.new('Fire')
f.Size=8
f.Heat=7
f.Color = BrickColor.new("Bright pink").Color;
f.SecondaryColor = BrickColor.new("Really red").Color;
f.Parent=game.Players.LocalPlayer.Character["Left Leg"]