--First Things First, What settings do you want?
Teams = true -- set this to false if there are no teams in the game
TeamName = "Nazis" --Personal fav
TeamColor = "Copper" --Random Color for me
BaseColor = "Medium stone grey" -- gud for a Base
MilitaryColor1 = "Black"
MilitaryColor2 = "Really black"
MilitaryColor3 = "Earth green"
SpawnColor = "Copper" --Custom Spawn Color


for _, instance in pairs(game.Workspace:GetChildren()) do
		if (instance:IsA('SpawnLocation')) then
	instance:Destroy();
end
end
if Teams == true then
Team = Instance.new("Team")
Team.Parent = game.Teams
Team.Name = TeamName
Team.TeamColor = BrickColor.new(TeamColor)
game.Players.LocalPlayer.TeamColor = BrickColor.new(TeamColor)
game.Players.LocalPlayer.Team = Team
end

Base = Instance.new("Part")
Base.Parent = game.Workspace
Base.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(196.76, 134.17, -200.175) 
Base.Anchored = true
Base.CanCollide = true
Base.TopSurface = "SmoothNoOutlines"
Base.BottomSurface = "SmoothNoOutlines"
Base.FrontSurface = "SmoothNoOutlines"
Base.LeftSurface = "SmoothNoOutlines"
Base.RightSurface = "SmoothNoOutlines"
Base.BrickColor = BrickColor.new(BaseColor)
Base.Size = Vector3.new(117.28, 7.1, 70.43)
Base2 = Instance.new("Part")
Base2.Parent = game.Workspace
Base2.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(185.925, 138.22, -200.52) 
Base2.Anchored = true
Base2.CanCollide = true
Base2.TopSurface = "SmoothNoOutlines"
Base2.BottomSurface = "SmoothNoOutlines"
Base2.FrontSurface = "SmoothNoOutlines"
Base2.LeftSurface = "SmoothNoOutlines"
Base2.RightSurface = "SmoothNoOutlines"
Base2.BrickColor = BrickColor.new(MilitaryColor1)
Base2.Size = Vector3.new(88.17, 1, 47.34)
Base3 = Instance.new("Part")
Base3.Parent = game.Workspace
Base3.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(242.87, 138.22, -179.845) 
Base3.Anchored = true
Base3.CanCollide = true
Base3.TopSurface = "SmoothNoOutlines"
Base3.BottomSurface = "SmoothNoOutlines"
Base3.FrontSurface = "SmoothNoOutlines"
Base3.LeftSurface = "SmoothNoOutlines"
Base3.RightSurface = "SmoothNoOutlines"
Base3.BrickColor = BrickColor.new(MilitaryColor2)
Base3.Size = Vector3.new(12.74, 1, 9.49)
T1 = Instance.new("Part")
T1.Parent = game.Workspace
T1.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(245.65, 149.805, -179.885) 
T1.Anchored = true
T1.CanCollide = true
T1.TopSurface = "SmoothNoOutlines"
T1.BottomSurface = "SmoothNoOutlines"
T1.FrontSurface = "SmoothNoOutlines"
T1.LeftSurface = "SmoothNoOutlines"
T1.RightSurface = "SmoothNoOutlines"
T1.BrickColor = BrickColor.new(MilitaryColor2)
T1.Size = Vector3.new(6.7, 22.17, 6.01)
T2 = Instance.new("TrussPart")
T2.Parent = game.Workspace
T2.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(240.74, 150.665, -179.82) 
T2.Anchored = true
T2.CanCollide = true
T2.TopSurface = "SmoothNoOutlines"
T2.BottomSurface = "SmoothNoOutlines"
T2.FrontSurface = "SmoothNoOutlines"
T2.LeftSurface = "SmoothNoOutlines"
T2.RightSurface = "SmoothNoOutlines"
T2.BrickColor = BrickColor.new(MilitaryColor1)
T2.Size = Vector3.new(2, 20.21, 2)
T3 = Instance.new("Part")
T3.Parent = game.Workspace
T3.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(244.99, 161.39, -179.845) 
T3.Anchored = true
T3.CanCollide = true
T3.TopSurface = "SmoothNoOutlines"
T3.BottomSurface = "SmoothNoOutlines"
T3.FrontSurface = "SmoothNoOutlines"
T3.LeftSurface = "SmoothNoOutlines"
T3.RightSurface = "SmoothNoOutlines"
T3.BrickColor = BrickColor.new(MilitaryColor2)
T3.Size = Vector3.new(8.5, 1, 9.49)
T4 = Instance.new("Part")
T4.Parent = game.Workspace
T4.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(244.99, 163.11, -184.055) 
T4.Anchored = true
T4.CanCollide = true
T4.TopSurface = "SmoothNoOutlines"
T4.BottomSurface = "SmoothNoOutlines"
T4.FrontSurface = "SmoothNoOutlines"
T4.LeftSurface = "SmoothNoOutlines"
T4.RightSurface = "SmoothNoOutlines"
T4.BrickColor = BrickColor.new(MilitaryColor2)
T4.Size = Vector3.new(8.5, 2.44, 1.07)
T5 = Instance.new("Part")
T5.Parent = game.Workspace
T5.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(248.76, 163.1, -179.85) 
T5.Anchored = true
T5.CanCollide = true
T5.TopSurface = "SmoothNoOutlines"
T5.BottomSurface = "SmoothNoOutlines"
T5.FrontSurface = "SmoothNoOutlines"
T5.LeftSurface = "SmoothNoOutlines"
T5.RightSurface = "SmoothNoOutlines"
T5.BrickColor = BrickColor.new(MilitaryColor2)
T5.Size = Vector3.new(0.96, 2.42, 7.02)
T6 = Instance.new("Part")
T6.Parent = game.Workspace
T6.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(244.99, 163.1, -175.685) 
T6.Anchored = true
T6.CanCollide = true
T6.TopSurface = "SmoothNoOutlines"
T6.BottomSurface = "SmoothNoOutlines"
T6.FrontSurface = "SmoothNoOutlines"
T6.LeftSurface = "SmoothNoOutlines"
T6.RightSurface = "SmoothNoOutlines"
T6.BrickColor = BrickColor.new(MilitaryColor2)
T6.Size = Vector3.new(8.5, 2.42, 1.07)
S1 = Instance.new("SpawnLocation")
S1.Parent = game.Workspace
S1.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(239.6, 138.22, -225.41) 
S1.Anchored = true
S1.CanCollide = false
S1.Transparency = 1
S1.TopSurface = "SmoothNoOutlines"
S1.BottomSurface = "SmoothNoOutlines"
S1.FrontSurface = "SmoothNoOutlines"
S1.LeftSurface = "SmoothNoOutlines"
S1.RightSurface = "SmoothNoOutlines"
S1.Size = Vector3.new(6, 1, 6)
if Teams == true then
S1.TeamColor = BrickColor.new(SpawnColor)
S1.Neutral = false
S1.AllowTeamChangeOnTouch = false
end

P1 = Instance.new("Part")
P1.Parent = game.Workspace
P1.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(228.655, 146.61, -191.57) 
P1.Anchored = true
P1.CanCollide = true
P1.TopSurface = "SmoothNoOutlines"
P1.BottomSurface = "SmoothNoOutlines"
P1.FrontSurface = "SmoothNoOutlines"
P1.LeftSurface = "SmoothNoOutlines"
P1.RightSurface = "SmoothNoOutlines"
P1.BrickColor = BrickColor.new(MilitaryColor1)
P1.Size = Vector3.new(24.11, 15.78, 2.48)
P1.Rotation = Vector3.new(0, 90, 0)
P2 = Instance.new("Part")
P2.Parent = game.Workspace
P2.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(143.025, 146.61, -200.57) 
P2.Anchored = true
P2.CanCollide = true
P2.TopSurface = "SmoothNoOutlines"
P2.BottomSurface = "SmoothNoOutlines"
P2.FrontSurface = "SmoothNoOutlines"
P2.LeftSurface = "SmoothNoOutlines"
P2.RightSurface = "SmoothNoOutlines"
P2.BrickColor = BrickColor.new(MilitaryColor1)
P2.Size = Vector3.new(41.99, 15.78, 2.48)
P2.Rotation = Vector3.new(0, 90, 0)
P3 = Instance.new("Part")
P3.Parent = game.Workspace
P3.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(186.08, 146.61, -178) 
P3.Anchored = true
P3.CanCollide = true
P3.TopSurface = "SmoothNoOutlines"
P3.BottomSurface = "SmoothNoOutlines"
P3.FrontSurface = "SmoothNoOutlines"
P3.LeftSurface = "SmoothNoOutlines"
P3.RightSurface = "SmoothNoOutlines"
P3.BrickColor = BrickColor.new(MilitaryColor1)
P3.Size = Vector3.new(87.86, 15.78, 2.48)
P3.Rotation = Vector3.new(0, 0, 0)
P4 = Instance.new("Part")
P4.Parent = game.Workspace
P4.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(186.08, 146.61, -222.89) 
P4.Anchored = true
P4.CanCollide = true
P4.TopSurface = "SmoothNoOutlines"
P4.BottomSurface = "SmoothNoOutlines"
P4.FrontSurface = "SmoothNoOutlines"
P4.LeftSurface = "SmoothNoOutlines"
P4.RightSurface = "SmoothNoOutlines"
P4.BrickColor = BrickColor.new(MilitaryColor1)
P4.Size = Vector3.new(87.86, 15.78, 2.48)
P4.Rotation = Vector3.new(0, 0, 0)

H1 = Instance.new("Part")
H1.Parent = game.Workspace
H1.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(210.33, 139.22, -188.965) 
H1.Anchored = true
H1.CanCollide = true
H1.TopSurface = "SmoothNoOutlines"
H1.BottomSurface = "SmoothNoOutlines"
H1.FrontSurface = "SmoothNoOutlines"
H1.LeftSurface = "SmoothNoOutlines"
H1.RightSurface = "SmoothNoOutlines"
H1.BrickColor = BrickColor.new(MilitaryColor3)
H1.Size = Vector3.new(14.64, 1, 16.47)
H1.Rotation = Vector3.new(0, 0, 0)
H2 = Instance.new("Part")
H2.Parent = game.Workspace
H2.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(210.355, 143.84, -181.435) 
H2.Anchored = true
H2.CanCollide = true
H2.TopSurface = "SmoothNoOutlines"
H2.BottomSurface = "SmoothNoOutlines"
H2.FrontSurface = "SmoothNoOutlines"
H2.LeftSurface = "SmoothNoOutlines"
H2.RightSurface = "SmoothNoOutlines"
H2.BrickColor = BrickColor.new(MilitaryColor3)
H2.Size = Vector3.new(11.97, 8.24, 1.41)
H2.Rotation = Vector3.new(0, 0, 0)
H3 = Instance.new("Part")
H3.Parent = game.Workspace
H3.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(217.065, 143.825, -188.965) 
H3.Anchored = true
H3.CanCollide = true
H3.TopSurface = "SmoothNoOutlines"
H3.BottomSurface = "SmoothNoOutlines"
H3.FrontSurface = "SmoothNoOutlines"
H3.LeftSurface = "SmoothNoOutlines"
H3.RightSurface = "SmoothNoOutlines"
H3.BrickColor = BrickColor.new(MilitaryColor3)
H3.Size = Vector3.new(1.17, 8.21, 16.47)
H3.Rotation = Vector3.new(0, 0, 0)
H4 = Instance.new("Part")
H4.Parent = game.Workspace
H4.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(203.625, 143.825, -188.965) 
H4.Anchored = true
H4.CanCollide = true
H4.TopSurface = "SmoothNoOutlines"
H4.BottomSurface = "SmoothNoOutlines"
H4.FrontSurface = "SmoothNoOutlines"
H4.LeftSurface = "SmoothNoOutlines"
H4.RightSurface = "SmoothNoOutlines"
H4.BrickColor = BrickColor.new(MilitaryColor3)
H4.Size = Vector3.new(1.17, 8.21, 16.47)
H4.Rotation = Vector3.new(0, 0, 0)
H5 = Instance.new("Part")
H5.Parent = game.Workspace
H5.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(208.235, 143.84, -196.375) 
H5.Anchored = true
H5.CanCollide = true
H5.TopSurface = "SmoothNoOutlines"
H5.BottomSurface = "SmoothNoOutlines"
H5.FrontSurface = "SmoothNoOutlines"
H5.LeftSurface = "SmoothNoOutlines"
H5.RightSurface = "SmoothNoOutlines"
H5.BrickColor = BrickColor.new(MilitaryColor3)
H5.Size = Vector3.new(7.67, 8.24, 1.41)
H5.Rotation = Vector3.new(0, 0, 0)
H6 = Instance.new("Part")
H6.Parent = game.Workspace
H6.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(206.98, 140.22, -188.26) 
H6.Anchored = true
H6.CanCollide = true
H6.TopSurface = "SmoothNoOutlines"
H6.BottomSurface = "SmoothNoOutlines"
H6.FrontSurface = "SmoothNoOutlines"
H6.LeftSurface = "SmoothNoOutlines"
H6.RightSurface = "SmoothNoOutlines"
H6.BrickColor = BrickColor.new("Medium stone grey")
H6.Size = Vector3.new(4, 1, 8.88)
H6.Rotation = Vector3.new(0, 0, 0)
H7 = Instance.new("Part")
H7.Parent = game.Workspace
H7.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(210.33, 148.46, -188.965) 
H7.Anchored = true
H7.CanCollide = true
H7.TopSurface = "SmoothNoOutlines"
H7.BottomSurface = "SmoothNoOutlines"
H7.FrontSurface = "SmoothNoOutlines"
H7.LeftSurface = "SmoothNoOutlines"
H7.RightSurface = "SmoothNoOutlines"
H7.BrickColor = BrickColor.new(MilitaryColor3)
H7.Size = Vector3.new(14.64, 1, 16.47)
H7.Rotation = Vector3.new(0, 0, 0)

H8 = Instance.new("Part")
H8.Parent = game.Workspace
H8.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(210.33, 139.22, -188.965) + Vector3.new(-18.48,0,0)
H8.Anchored = true
H8.CanCollide = true
H8.TopSurface = "SmoothNoOutlines"
H8.BottomSurface = "SmoothNoOutlines"
H8.FrontSurface = "SmoothNoOutlines"
H8.LeftSurface = "SmoothNoOutlines"
H8.RightSurface = "SmoothNoOutlines"
H8.BrickColor = BrickColor.new(MilitaryColor3)
H8.Size = Vector3.new(14.64, 1, 16.47)
H8.Rotation = Vector3.new(0, 0, 0)
H9 = Instance.new("Part")
H9.Parent = game.Workspace
H9.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(210.355, 143.84, -181.435) + Vector3.new(-18.48,0,0)
H9.Anchored = true
H9.CanCollide = true
H9.TopSurface = "SmoothNoOutlines"
H9.BottomSurface = "SmoothNoOutlines"
H9.FrontSurface = "SmoothNoOutlines"
H9.LeftSurface = "SmoothNoOutlines"
H9.RightSurface = "SmoothNoOutlines"
H9.BrickColor = BrickColor.new(MilitaryColor3)
H9.Size = Vector3.new(11.97, 8.24, 1.41)
H9.Rotation = Vector3.new(0, 0, 0)
H10 = Instance.new("Part")
H10.Parent = game.Workspace
H10.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(217.065, 143.825, -188.965) + Vector3.new(-18.48,0,0)
H10.Anchored = true
H10.CanCollide = true
H10.TopSurface = "SmoothNoOutlines"
H10.BottomSurface = "SmoothNoOutlines"
H10.FrontSurface = "SmoothNoOutlines"
H10.LeftSurface = "SmoothNoOutlines"
H10.RightSurface = "SmoothNoOutlines"
H10.BrickColor = BrickColor.new(MilitaryColor3)
H10.Size = Vector3.new(1.17, 8.21, 16.47)
H10.Rotation = Vector3.new(0, 0, 0)
H11 = Instance.new("Part")
H11.Parent = game.Workspace
H11.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(203.625, 143.825, -188.965) + Vector3.new(-18.48,0,0)
H11.Anchored = true
H11.CanCollide = true
H11.TopSurface = "SmoothNoOutlines"
H11.BottomSurface = "SmoothNoOutlines"
H11.FrontSurface = "SmoothNoOutlines"
H11.LeftSurface = "SmoothNoOutlines"
H11.RightSurface = "SmoothNoOutlines"
H11.BrickColor = BrickColor.new(MilitaryColor3)
H11.Size = Vector3.new(1.17, 8.21, 16.47)
H11.Rotation = Vector3.new(0, 0, 0)
H12 = Instance.new("Part")
H12.Parent = game.Workspace
H12.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(208.235, 143.84, -196.375) + Vector3.new(-18.48,0,0)
H12.Anchored = true
H12.CanCollide = true
H12.TopSurface = "SmoothNoOutlines"
H12.BottomSurface = "SmoothNoOutlines"
H12.FrontSurface = "SmoothNoOutlines"
H12.LeftSurface = "SmoothNoOutlines"
H12.RightSurface = "SmoothNoOutlines"
H12.BrickColor = BrickColor.new(MilitaryColor3)
H12.Size = Vector3.new(7.67, 8.24, 1.41)
H12.Rotation = Vector3.new(0, 0, 0)
H13 = Instance.new("Part")
H13.Parent = game.Workspace
H13.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(206.98, 140.22, -188.26) + Vector3.new(-18.48,0,0)
H13.Anchored = true
H13.CanCollide = true
H13.TopSurface = "SmoothNoOutlines"
H13.BottomSurface = "SmoothNoOutlines"
H13.FrontSurface = "SmoothNoOutlines"
H13.LeftSurface = "SmoothNoOutlines"
H13.RightSurface = "SmoothNoOutlines"
H13.BrickColor = BrickColor.new("Medium stone grey")
H13.Size = Vector3.new(4, 1, 8.88)
H13.Rotation = Vector3.new(0, 0, 0)
H14 = Instance.new("Part")
H14.Parent = game.Workspace
H14.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(210.33, 148.46, -188.965) + Vector3.new(-18.48,0,0)
H14.Anchored = true
H14.CanCollide = true
H14.TopSurface = "SmoothNoOutlines"
H14.BottomSurface = "SmoothNoOutlines"
H14.FrontSurface = "SmoothNoOutlines"
H14.LeftSurface = "SmoothNoOutlines"
H14.RightSurface = "SmoothNoOutlines"
H14.BrickColor = BrickColor.new(MilitaryColor3)
H14.Size = Vector3.new(14.64, 1, 16.47)
H14.Rotation = Vector3.new(0, 0, 0)
B1 = Instance.new("Part")
B1.Parent = game.Workspace
B1.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(171.335, 141.305, -183.95)
B1.Anchored = true
B1.CanCollide = true
B1.TopSurface = "SmoothNoOutlines"
B1.BottomSurface = "SmoothNoOutlines"
B1.FrontSurface = "SmoothNoOutlines"
B1.LeftSurface = "SmoothNoOutlines"
B1.RightSurface = "SmoothNoOutlines"
B1.BrickColor = BrickColor.new("Reddish brown")
B1.Size = Vector3.new(5.93, 5.17, 5.84)
B1.Rotation = Vector3.new(0, 0, 0)
B2 = Instance.new("Part")
B2.Parent = game.Workspace
B2.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(164.435, 141.305, -183.95)
B2.Anchored = true
B2.CanCollide = true
B2.TopSurface = "SmoothNoOutlines"
B2.BottomSurface = "SmoothNoOutlines"
B2.FrontSurface = "SmoothNoOutlines"
B2.LeftSurface = "SmoothNoOutlines"
B2.RightSurface = "SmoothNoOutlines"
B2.BrickColor = BrickColor.new("Reddish brown")
B2.Size = Vector3.new(5.93, 5.17, 5.84)
B2.Rotation = Vector3.new(0, 0, 0)
B3 = Instance.new("Part")
B3.Parent = game.Workspace
B3.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(168.285, 146.475, -183.95)
B3.Anchored = true
B3.CanCollide = true
B3.TopSurface = "SmoothNoOutlines"
B3.BottomSurface = "SmoothNoOutlines"
B3.FrontSurface = "SmoothNoOutlines"
B3.LeftSurface = "SmoothNoOutlines"
B3.RightSurface = "SmoothNoOutlines"
B3.BrickColor = BrickColor.new("Reddish brown")
B3.Size = Vector3.new(5.93, 5.17, 5.84)
B3.Rotation = Vector3.new(0, 0, 0)
A1 = Instance.new("Part")
A1.Parent = game.Workspace
A1.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(157.15, 139.22, -205.295)
A1.Anchored = true
A1.CanCollide = true
A1.TopSurface = "SmoothNoOutlines"
A1.BottomSurface = "SmoothNoOutlines"
A1.FrontSurface = "SmoothNoOutlines"
A1.LeftSurface = "SmoothNoOutlines"
A1.RightSurface = "SmoothNoOutlines"
A1.BrickColor = BrickColor.new(MilitaryColor2)
A1.Size = Vector3.new(15.5, 1, 24.59)
A1.Rotation = Vector3.new(0, 0, 0)
A2 = Instance.new("Part")
A2.Parent = game.Workspace
A2.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(164.325, 143.535, -202.02)
A2.Anchored = true
A2.CanCollide = true
A2.TopSurface = "SmoothNoOutlines"
A2.BottomSurface = "SmoothNoOutlines"
A2.FrontSurface = "SmoothNoOutlines"
A2.LeftSurface = "SmoothNoOutlines"
A2.RightSurface = "SmoothNoOutlines"
A2.BrickColor = BrickColor.new(MilitaryColor2)
A2.Size = Vector3.new(0.87, 7.63, 15.86)
A2.Rotation = Vector3.new(0, 0, 0)
A3 = Instance.new("Part")
A3.Parent = game.Workspace
A3.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(157.15, 143.515, -193.48)
A3.Anchored = true
A3.CanCollide = true
A3.TopSurface = "SmoothNoOutlines"
A3.BottomSurface = "SmoothNoOutlines"
A3.FrontSurface = "SmoothNoOutlines"
A3.LeftSurface = "SmoothNoOutlines"
A3.RightSurface = "SmoothNoOutlines"
A3.BrickColor = BrickColor.new(MilitaryColor2)
A3.Size = Vector3.new(15.5, 7.59, 0.96)
A3.Rotation = Vector3.new(0, 0, 0)
A4 = Instance.new("Part")
A4.Parent = game.Workspace
A4.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(149.835, 143.51, -205.27)
A4.Anchored = true
A4.CanCollide = true
A4.TopSurface = "SmoothNoOutlines"
A4.BottomSurface = "SmoothNoOutlines"
A4.FrontSurface = "SmoothNoOutlines"
A4.LeftSurface = "SmoothNoOutlines"
A4.RightSurface = "SmoothNoOutlines"
A4.BrickColor = BrickColor.new(MilitaryColor2)
A4.Size = Vector3.new(0.87, 7.58, 22.36)
A4.Rotation = Vector3.new(0, 0, 0)
A5 = Instance.new("Part")
A5.Parent = game.Workspace
A5.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(157.15, 143.47, -217.13)
A5.Anchored = true
A5.CanCollide = true
A5.TopSurface = "SmoothNoOutlines"
A5.BottomSurface = "SmoothNoOutlines"
A5.FrontSurface = "SmoothNoOutlines"
A5.LeftSurface = "SmoothNoOutlines"
A5.RightSurface = "SmoothNoOutlines"
A5.BrickColor = BrickColor.new(MilitaryColor2)
A5.Size = Vector3.new(15.5, 7.5, 0.96)
A5.Rotation = Vector3.new(0, 0, 0)
A6 = Instance.new("Part")
A6.Parent = game.Workspace
A6.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(157.15, 147.85, -205.295)
A6.Anchored = true
A6.CanCollide = true
A6.TopSurface = "SmoothNoOutlines"
A6.BottomSurface = "SmoothNoOutlines"
A6.FrontSurface = "SmoothNoOutlines"
A6.LeftSurface = "SmoothNoOutlines"
A6.RightSurface = "SmoothNoOutlines"
A6.BrickColor = BrickColor.new(MilitaryColor2)
A6.Size = Vector3.new(15.5, 1, 24.59)
A6.Rotation = Vector3.new(0, 0, 0)
A7 = Instance.new("Part")
A7.Parent = game.Workspace
A7.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(157.06, 141.21, -196.45)
A7.Anchored = true
A7.CanCollide = true
A7.TopSurface = "SmoothNoOutlines"
A7.BottomSurface = "SmoothNoOutlines"
A7.FrontSurface = "SmoothNoOutlines"
A7.LeftSurface = "SmoothNoOutlines"
A7.RightSurface = "SmoothNoOutlines"
A7.BrickColor = BrickColor.new("Reddish brown")
A7.Size = Vector3.new(10.8, 2.98, 4)
A7.Rotation = Vector3.new(0, 0, 0)
SS1 = Instance.new("Seat")
SS1.Parent = game.Workspace
SS1.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(157.22, 140.49, -201.205)
SS1.Anchored = true
SS1.CanCollide = true
SS1.TopSurface = "SmoothNoOutlines"
SS1.BottomSurface = "SmoothNoOutlines"
SS1.FrontSurface = "SmoothNoOutlines"
SS1.LeftSurface = "SmoothNoOutlines"
SS1.RightSurface = "SmoothNoOutlines"
SS1.BrickColor = BrickColor.new("Burnt Sienna")
SS1.Size = Vector3.new(3.3, 1.54, 2.27)
SS1.Rotation = Vector3.new(-180, 0, -180)
SS2 = Instance.new("Seat")
SS2.Parent = game.Workspace
SS2.Position = game.Players.LocalPlayer.Character.Torso.Position + Vector3.new(157.19, 142.99, -202.9)
SS2.Anchored = true
SS2.CanCollide = true
SS2.TopSurface = "SmoothNoOutlines"
SS2.BottomSurface = "SmoothNoOutlines"
SS2.FrontSurface = "SmoothNoOutlines"
SS2.LeftSurface = "SmoothNoOutlines"
SS2.RightSurface = "SmoothNoOutlines"
SS2.BrickColor = BrickColor.new("Burnt Sienna")
SS2.Size = Vector3.new(3.68, 4.1, 0.8)
SS2.Rotation = Vector3.new(0, 0, 0)




c = game.Players.LocalPlayer
c:LoadCharacter()