local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(25, 1, 25) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(5, 0.1, 25) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(25, 9, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(5, 2, 13) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(25, 9, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(5, 2, 37) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 9, 9) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(17, 2, 18) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 9, 9) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(17, 2, 32) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Reddish brown")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 9, 5) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(17, 2, 25) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = false -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 9, 23) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-7, 2, 25) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(25, 1, 25) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(5, 2, 25) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Reddish brown")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 2, 2) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(1, 2, 25) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Reddish brown")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(5, 1, 8) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(1, 2, 25) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Bright blue")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Shape = 0
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(1, 5, 23) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Bright blue")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Shape = 0
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(2, 5, 23) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Bright blue")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Shape = 0
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(1.5, 5, 23) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("Black")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(9, 1, 7) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-2, 1, 17) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.BrickColor=BrickColor.new("White")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 1, 7) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-5.5, 1, 17) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Seat")
brick.BrickColor=BrickColor.new("Reddish brown")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 1, 2) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(5.5, 1, 25) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = false -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Seat")
brick.BrickColor=BrickColor.new("Reddish brown")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 1, 2) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-3.5, 1, 25) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = false -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1