local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 18, 36) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-15.5, 10.2, 0.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(32, 1.2, 36) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-0.5, 0.6, 0.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 18, 36) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(14.5, 10.2, 0.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(28, 18, 2) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-0.5, 10.2, -16.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(10, 18, 2) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(8.5, 10.2, 17.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(10, 18, 2) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-9.5, 10.2, 17.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(32, 1.2, 36) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-0.5, 19.8, 0.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 1.2, 10) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-15, 21, 12.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 1.2, 10) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-10, 21, 12.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 1.2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-11, 21, 7) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 1.2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-14, 21, 7) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 1.2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-12.5, 21, 6) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(4, 1.2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-12.5, 21, 12) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 1.2, 10) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-8, 21, 11.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(6, 1.2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-4.5, 21, 17) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(6, 1.2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-4.5, 21, 6) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 1.2, 12) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-1.49e-008, 21, 11.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(5, 1.2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(3, 21, 6) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(5, 1.2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(3, 21, 17) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 1.2, 4) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(6, 21, 14.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 1.2, 4) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(6, 21, 8.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(5, 1.2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(3, 21, 11) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(5, 1.2, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(3, 21, 12) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 1 -- makes it non-shiny to shiny  0 - 1