m = Instance.new("Model") 
m.Parent = workspace.acb227
m.Name = "Jaily" 

local h = Instance.new("Part") 
h.Name = "Handle" 
h.Anchored = true
h.Parent = m 
h.Size = Vector3.new(25,1,25) 
h.CFrame = workspace.Base.CFrame + Vector3.new(0, 90, 0)
h.formFactor = "Brick" 
h.BrickColor = BrickColor.new("Really black") 
m = Instance.new("BlockMesh") 
m.Parent = h 
m.Scale = Vector3.new(1.1, 1.1, 1.1) 
local h = Instance.new("Part") 
h.Name = "Handle" 
h.Anchored = true
h.Parent = m 
h.Size = Vector3.new(1,18,25) 
h.CFrame = workspace.Base.CFrame + Vector3.new(13.5, 100, 0)
h.formFactor = "Brick" 
h.BrickColor = BrickColor.new("Really black") 
m = Instance.new("BlockMesh") 
m.Parent = h 
m.Scale = Vector3.new(1.1, 1.1, 1.1) 
local h = Instance.new("Part") 
h.Name = "Handle" 
h.Anchored = true
h.Parent = m 
h.Size = Vector3.new(1,18,25) 
h.CFrame = workspace.Base.CFrame + Vector3.new(-13.5, 100, 0)
h.formFactor = "Brick" 
h.BrickColor = BrickColor.new("Really black") 
m = Instance.new("BlockMesh") 
m.Parent = h 
m.Scale = Vector3.new(1.1, 1.1, 1.1) 
local h = Instance.new("Part") 
h.Name = "Handle" 
h.Anchored = true
h.Parent = m 
h.Size = Vector3.new(25,18,1) 
h.CFrame = workspace.Base.CFrame + Vector3.new(0, 100, 13.5)
h.formFactor = "Brick" 
h.BrickColor = BrickColor.new("Really black") 
m = Instance.new("BlockMesh") 
m.Parent = h 
m.Scale = Vector3.new(1.1, 1.1, 1.1) 
local h = Instance.new("Part") 
h.Name = "Handle" 
h.Anchored = true
h.Parent = m 
h.Size = Vector3.new(25,18,1) 
h.CFrame = workspace.Base.CFrame + Vector3.new(0, 100, -13.5)
h.formFactor = "Brick" 
h.BrickColor = BrickColor.new("Really black") 
m = Instance.new("BlockMesh") 
m.Parent = h 
m.Scale = Vector3.new(1.1, 1.1, 1.1) 
local h = Instance.new("Part") 
h.Name = "Handle" 
h.Anchored = true
h.Parent = m 
h.Size = Vector3.new(25,1,25) 
h.CFrame = workspace.Base.CFrame + Vector3.new(0, 109, 0)
h.formFactor = "Brick" 
h.BrickColor = BrickColor.new("Really black") 
m = Instance.new("BlockMesh") 
m.Parent = h 
m.Scale = Vector3.new(1.1, 1.1, 1.1) 