										
										
t=Instance.new("Tool") 
t.Parent = game.Players.lordsheen.Backpack 
t.Name = "Lightsaber" 
s=Instance.new("Part") 
s.Parent = t 
s.CanCollide = true 
s.Size = Vector3.new(2,2,2) 
s.Name = "Handle" 
s.BrickColor = BrickColor.new(1)
s.Transparency = 1 
g=Instance.new("Part") 
g.Parent = t 
g.CanCollide = false 
g.Size = Vector3.new(1,1,1) 
g.Name = "Handle" 
g.BrickColor = BrickColor.new("Really black") 
c=Instance.new("Part") 
c.Parent = t 
c.CanCollide = false 
c.Size = Vector3.new(1,8,1) 
c.Name = "Handle" 
c.BrickColor = BrickColor.new("Royal blue") 
c.Transparency = 0.3 
h=Instance.new("Part") 
h.Parent = t 
h.CanCollide = false 
h.Size = Vector3.new(1,8,1) 
h.Name = "Handle" 
h.BrickColor = BrickColor.new("Really black") 
h.Transparency = 0.5  
local w = Instance.new("Weld") 
w.Part1 = g 
w.Part0 = c 
local C1 = c.CFrame 
local C0 = c.CFrame + Vector3.new(0,0,0) 
w.C1 = C1 
w.C0 = C0 
w.Parent = g 
local w = Instance.new("Weld") 
w.Part1 = g 
w.Part0 = h 
local C1 = h.CFrame 
local C0 = h.CFrame + Vector3.new(0,0,0) 
w.C1 = C1 
w.C0 = C0 
w.Parent = g 
Mesh = Instance.new("SpecialMesh") 
Mesh.MeshType = "Head" 
Mesh.Parent = c 
Mesh = Instance.new("SpecialMesh") 
Mesh.MeshType = "Head" 
Mesh.Scale = Vector3.new(0.65,0.95,0.65) 
Mesh.Parent = h 
DS = Instance.new("Motor6D") 
DS.Parent = s 
DS.Part0 = s --holds 
DS.Part1 = g --spins 
DS.Name = "Neck" 
DS.DesiredAngle = 1000000000000000000000000000000 
DS.MaxVelocity = 0.2 