local Me = game.Players.LocalPlayer 
local megui = Me.PlayerGui  
local resc = 350 
local count = 0 

local main = Instance.new("GuiMain") 
main.Parent = megui 
main.Name = "GameGui" 
local framer = Instance.new("Frame", main) 
framer.BackgroundColor3 = Color3.new(0.15, 0.15, 0.15)
framer.BorderColor3 = Color3.new(0, 0, 0)
framer.BorderSizePixel = 1 
framer.Name = "Content"
framer.Position = UDim2.new(0, 0, 1, -175/2)
framer.Size = UDim2.new(1, 0, 0, 175)
local text = Instance.new("TextLabel") 
text.Parent = framer 
text.BackgroundColor3 = Color3.new(2, 2, 2) 
text.BorderColor3 = Color3.new(0, 0, 0) 
text.BorderSizePixel = 1
text.Name = "Name"
text.Position = UDim2.new(0, 0, 0, 0) 
text.Text = "Buildings: " 
text.Size = UDim2.new(0, 100, 0, 25)
local text = Instance.new("TextLabel") 
text.Parent = framer 
text.BackgroundColor3 = Color3.new(1, 2, 0) 
text.BorderColor3 = Color3.new(0, 0, 0) 
text.BorderSizePixel = 1
text.Name = "Name"
text.Position = UDim2.new(0, 100, 0, 0) 
text.Text = "SteamPlant: 50" 
text.Size = UDim2.new(0, 100, 0, 25)
local text = Instance.new("TextLabel") 
text.Parent = framer 
text.BackgroundColor3 = Color3.new(1, 2, 0) 
text.BorderColor3 = Color3.new(0, 0, 0) 
text.BorderSizePixel = 1
text.Name = "Name"
text.Position = UDim2.new(0, 200, 0, 0) 
text.Text = "War Factory: 250" 
text.Size = UDim2.new(0, 100, 0, 25)
local text = Instance.new("TextLabel") 
text.Parent = framer 
text.BackgroundColor3 = Color3.new(1, 2, 0) 
text.BorderColor3 = Color3.new(0, 0, 0) 
text.BorderSizePixel = 1
text.Name = "Name"
text.Position = UDim2.new(0, 300, 0, 0) 
text.Text = "HQ: 500" 
text.Size = UDim2.new(0, 100, 0, 25)
local text = Instance.new("TextLabel") 
text.Parent = framer 
text.BackgroundColor3 = Color3.new(1, 2, 0) 
text.BorderColor3 = Color3.new(0, 0, 0) 
text.BorderSizePixel = 1
text.Name = "Name"
text.Position = UDim2.new(0, 400, 0, 0) 
text.Text = "Air Field: 400" 
text.Size = UDim2.new(0, 100, 0, 25)
local text = Instance.new("TextLabel") 
text.Parent = framer 
text.BackgroundColor3 = Color3.new(1, 2, 0) 
text.BorderColor3 = Color3.new(0, 0, 0) 
text.BorderSizePixel = 1
text.Name = "Name"
text.Position = UDim2.new(0, 0, 0, 25) 
text.Text = "Barracks: 200" 
text.Size = UDim2.new(0, 100, 0, 25)
local text2 = Instance.new("TextLabel") 
text2.Parent = framer 
text2.BackgroundColor3 = Color3.new(1, 2, 0) 
text2.BorderColor3 = Color3.new(0, 0, 0) 
text2.BorderSizePixel = 1
text2.Name = "Name"
text2.Position = UDim2.new(0, 100, 0, 25) 
text2.Text = "Resources: " ..resc.. " " 
text2.Size = UDim2.new(0, 100, 0, 25) 

local modl = Instance.new("Model", workspace.Base) 
local health = Instance.new("IntValue") 
health.Parent = modl 
health.Value = 100 
modl.Name = "HQ - " ..Me.Name.. " " 
local hum = Instance.new("Humanoid", modl) 
hum.MaxHealth = 0 
hum.Health = 0 
local parta = Instance.new("Part") 
parta.Name = "Torso" 
parta.Parent = modl 
parta.Anchored = true 
parta.BrickColor = BrickColor.new("White") 
parta.formFactor = "Custom" 
parta.Size = Vector3.new(10, 1, 10) 
parta.CFrame = CFrame.new(math.random(-25, 25), math.random(0.55, 0.6), math.random(-25, 25)) 
local partm = Instance.new("BlockMesh") 
partm.Parent = parta
partm.Bevel = 0.1 
local partb = Instance.new("Part") 
partb.Parent = modl 
partb.Anchored = true 
partb.BrickColor = BrickColor.new("Dark stone grey") 
partb.formFactor = "Custom" 
partb.Name = "Head" 
partb.Size = Vector3.new(7, 5, 7) 
partb.CFrame = parta.CFrame + Vector3.new(0, 2.5, 0) 
local gui = Instance.new("BillboardGui")
gui.Parent = modl
gui.Adornee = partb
gui.Size = UDim2.new(1, 0, 1, 0)
gui.StudsOffset = Vector3.new(0, 3, 0) 
	local frame = Instance.new("Frame")
	frame.Parent = gui
	frame.Size = UDim2.new(1, 0, 1, 0)
	frame.BackgroundTransparency = 1
local text = Instance.new("TextLabel") text.Parent = frame text.Size = UDim2.new(1, 0, 1, 0) text.BackgroundTransparency = 1 text.Text = "Health" ..health.Value 
text.FontSize = "Size14" 
local parbm = Instance.new("BlockMesh") 
parbm.Parent = partb
parbm.Bevel = 0.1 
local partc = Instance.new("Part") 
partc.Parent = modl 
partc.Anchored = true 
partc.BrickColor = Me.Character.Torso.BrickColor 
partc.formFactor = "Custom" 
partc.Size = Vector3.new(7.2, 1, 7.2) 
partc.CFrame = parta.CFrame + Vector3.new(0, 1.5, 0) 
local parcm = Instance.new("BlockMesh") 
parcm.Parent = partc
parcm.Bevel = 0.1 
local partd = Instance.new("Part") 
partd.Parent = modl 
partd.Anchored = true 
partd.BrickColor = Me.Character.Torso.BrickColor 
partd.formFactor = "Custom" 
partd.Size = Vector3.new(7.2, 1, 7.2) 
partd.CFrame = parta.CFrame + Vector3.new(0, 3.5, 0) 
local pardm = Instance.new("BlockMesh") 
pardm.Parent = partd
pardm.Bevel = 0.1 

if script.Parent.className ~= "HopperBin" then
    local h = Instance.new("HopperBin", Me.Backpack)
    h.Name = "Game"
    script.Parent = h
end

local bin = script.Parent

function onSelected(mouse) 
    mouse.Button1Down:connect(function()
    end)
    mouse.KeyDown:connect(function(key)
        if key == "q" and resc >= 500 then 
resc = resc - 500 
text2.Text = "Resources: " ..resc.. " " 
local modl = Instance.new("Model", workspace.Base) 
local health = Instance.new("IntValue") 
health.Parent = modl 
health.Value = 100 
modl.Name = "HQ - " ..Me.Name.. " " 
local hum = Instance.new("Humanoid", modl) 
hum.MaxHealth = 0 
hum.Health = 0 
local pos = mouse.hit.p 
local parta = Instance.new("Part") 
parta.Parent = modl 
parta.Anchored = true 
parta.Name = "Torso" 
parta.BrickColor = BrickColor.new("White") 
parta.formFactor = "Custom" 
parta.Size = Vector3.new(10, 1, 10) 
parta.CFrame = CFrame.new(pos) 
local partm = Instance.new("BlockMesh") 
partm.Parent = parta
partm.Bevel = 0.1 
local partb = Instance.new("Part") 
partb.Parent = modl 
partb.Anchored = true 
partb.BrickColor = BrickColor.new("Dark stone grey") 
partb.formFactor = "Custom" 
partb.Name = "Head" 
partb.Size = Vector3.new(7, 5, 7) 
partb.CFrame = parta.CFrame + Vector3.new(0, 2.5, 0) 
local gui = Instance.new("BillboardGui")
gui.Parent = modl
gui.Adornee = partb
gui.Size = UDim2.new(1, 0, 1, 0)
gui.StudsOffset = Vector3.new(0, 3, 0) 
	local frame = Instance.new("Frame")
	frame.Parent = gui
	frame.Size = UDim2.new(1, 0, 1, 0)
	frame.BackgroundTransparency = 1
local text = Instance.new("TextLabel") text.Parent = frame text.Size = UDim2.new(1, 0, 1, 0) text.BackgroundTransparency = 1 text.Text = "Health" ..health.Value 
text.FontSize = "Size14" 
local parbm = Instance.new("BlockMesh") 
parbm.Parent = partb
parbm.Bevel = 0.1 
local partc = Instance.new("Part") 
partc.Parent = modl 
partc.Anchored = true 
partc.BrickColor = Me.Character.Torso.BrickColor 
partc.formFactor = "Custom" 
partc.Size = Vector3.new(7.2, 1, 7.2) 
partc.CFrame = parta.CFrame + Vector3.new(0, 1.5, 0) 
local parcm = Instance.new("BlockMesh") 
parcm.Parent = partc
parcm.Bevel = 0.1 
local partd = Instance.new("Part") 
partd.Parent = modl 
partd.Anchored = true 
partd.BrickColor = Me.Character.Torso.BrickColor 
partd.formFactor = "Custom" 
partd.Size = Vector3.new(7.2, 1, 7.2) 
partd.CFrame = parta.CFrame + Vector3.new(0, 3.5, 0) 
local pardm = Instance.new("BlockMesh") 
pardm.Parent = partd
pardm.Bevel = 0.1 
	end 
	    if key == "e" and resc >= 200 then 
resc = resc - 200 
text2.Text = "Resources: " ..resc.. " " 
local modl = Instance.new("Model", workspace.Base) 
modl.Name = "Barracks - " ..Me.Name.. " " 
local health = Instance.new("IntValue") 
health.Parent = modl 
health.Value = 100 
local hum = Instance.new("Humanoid", modl) 
hum.MaxHealth = 0 
hum.Health = 0 
local pos = mouse.hit.p 
local parta = Instance.new("Part") 
parta.Parent = modl 
parta.Anchored = true 
parta.Name = "Torso" 
parta.BrickColor = BrickColor.new("White") 
parta.formFactor = "Custom" 
parta.Size = Vector3.new(7, 1, 7) 
parta.CFrame = CFrame.new(pos) 
local partm = Instance.new("BlockMesh") 
partm.Parent = parta
partm.Bevel = 0.1 
local partb = Instance.new("Part") 
partb.Parent = modl 
partb.Anchored = true 
partb.BrickColor = BrickColor.new("Dark stone grey") 
partb.formFactor = "Custom" 
partb.Name = "Head" 
partb.Size = Vector3.new(5, 3, 5) 
partb.CFrame = parta.CFrame + Vector3.new(0, 2.5, 0) 
local gui = Instance.new("BillboardGui")
gui.Parent = modl
gui.Adornee = partb
gui.Size = UDim2.new(1, 0, 1, 0)
gui.StudsOffset = Vector3.new(0, 3, 0) 
	local frame = Instance.new("Frame")
	frame.Parent = gui
	frame.Size = UDim2.new(1, 0, 1, 0)
	frame.BackgroundTransparency = 1
local text = Instance.new("TextLabel") text.Parent = frame text.Size = UDim2.new(1, 0, 1, 0) text.BackgroundTransparency = 1 text.Text = "Health" ..health.Value 
text.FontSize = "Size14" 
local parbm = Instance.new("BlockMesh") 
parbm.Parent = partb
parbm.Bevel = 0.1 
local partc = Instance.new("Part") 
partc.Parent = modl 
partc.Anchored = true 
partc.BrickColor = Me.Character.Torso.BrickColor 
partc.formFactor = "Custom" 
partc.Size = Vector3.new(5.2, 1, 5.2) 
partc.CFrame = parta.CFrame + Vector3.new(0, 0.5, 0) 
local parcm = Instance.new("BlockMesh") 
parcm.Parent = partc
parcm.Bevel = 0.1 
local partd = Instance.new("Part") 
partd.Parent = modl 
partd.Anchored = true 
partd.BrickColor = Me.Character.Torso.BrickColor 
partd.formFactor = "Custom" 
partd.Size = Vector3.new(5.2, 1, 5.2) 
partd.CFrame = parta.CFrame + Vector3.new(0, 1.5, 0) 
local pardm = Instance.new("BlockMesh") 
pardm.Parent = partd
pardm.Bevel = 0.1 
	end 
	    if key == "r" and resc >= 400 then 
resc = resc - 400 
text2.Text = "Resources: " ..resc.. " " 
local modl = Instance.new("Model", workspace.Base) 
modl.Name = "AirField - " ..Me.Name.. " " 
local health = Instance.new("IntValue") 
health.Parent = modl 
health.Value = 100 
local hum = Instance.new("Humanoid", modl) 
hum.MaxHealth = 0 
hum.Health = 0 
local pos = mouse.hit.p 
local parta = Instance.new("Part") 
parta.Parent = modl 
parta.Anchored = true 
parta.BrickColor = BrickColor.new("Black") 
parta.formFactor = "Custom" 
parta.Name = "Torso" 
parta.Size = Vector3.new(10, 1, 13) 
parta.CFrame = CFrame.new(pos) 
local partm = Instance.new("BlockMesh") 
partm.Parent = parta
partm.Bevel = 0.1 
local partb = Instance.new("Part") 
partb.Parent = modl 
partb.Anchored = true 
partb.BrickColor = BrickColor.new("Dark stone grey") 
partb.formFactor = "Custom" 
partb.Name = "Head" 
partb.Size = Vector3.new(4, 5, 4) 
partb.CFrame = parta.CFrame + Vector3.new(0, 2.5, 2) 
local gui = Instance.new("BillboardGui")
gui.Parent = modl
gui.Adornee = partb
gui.Size = UDim2.new(1, 0, 1, 0)
gui.StudsOffset = Vector3.new(0, 3, 0) 
	local frame = Instance.new("Frame")
	frame.Parent = gui
	frame.Size = UDim2.new(1, 0, 1, 0)
	frame.BackgroundTransparency = 1
local text = Instance.new("TextLabel") text.Parent = frame text.Size = UDim2.new(1, 0, 1, 0) text.BackgroundTransparency = 1 text.Text = "Health" ..health.Value 
text.FontSize = "Size14" 
local parbm = Instance.new("BlockMesh") 
parbm.Parent = partb
parbm.Bevel = 0.1 
local partc = Instance.new("Part") 
partc.Parent = modl 
partc.Anchored = true 
partc.BrickColor = Me.Character.Torso.BrickColor 
partc.formFactor = "Custom" 
partc.Size = Vector3.new(4.2, 1, 4.2) 
partc.CFrame = parta.CFrame + Vector3.new(0, 1.5, 2) 
local parcm = Instance.new("BlockMesh") 
parcm.Parent = partc
parcm.Bevel = 0.1 
local partd = Instance.new("Part") 
partd.Parent = modl 
partd.Anchored = true 
partd.BrickColor = Me.Character.Torso.BrickColor 
partd.formFactor = "Custom" 
partd.Size = Vector3.new(4.2, 1, 4.2) 
partd.CFrame = parta.CFrame + Vector3.new(0, 3.5, 2) 
local pardm = Instance.new("BlockMesh") 
pardm.Parent = partd
pardm.Bevel = 0.1 
	end 
	    if key == "t" and resc >= 50 then 
resc = resc - 50 
text2.Text = "Resources: " ..resc.. " " 
count = count + 1
local modl = Instance.new("Model", workspace.Base) 
modl.Name = "SteamPlant - " ..Me.Name.. " " 
local hum = Instance.new("Humanoid", modl) 
hum.MaxHealth = 0 
hum.Health = 0 
local health = Instance.new("IntValue") 
health.Parent = modl 
health.Value = 100 
local pos = mouse.hit.p 
local parta = Instance.new("Part") 
parta.Parent = modl 
parta.Anchored = true 
parta.Name = "Torso" 
parta.BrickColor = BrickColor.new("Black") 
parta.formFactor = "Custom" 
parta.Size = Vector3.new(3, 1, 3) 
parta.CFrame = CFrame.new(pos) 
local partm = Instance.new("BlockMesh") 
partm.Parent = parta
partm.Bevel = 0.1 
local partb = Instance.new("Part") 
partb.Parent = modl 
partb.Anchored = true 
partb.BrickColor = BrickColor.new("Dark stone grey") 
partb.formFactor = "Custom" 
partb.Name = "Head" 
partb.Size = Vector3.new(2, 2, 2) 
partb.CFrame = parta.CFrame + Vector3.new(0, 1, 0) 
local gui = Instance.new("BillboardGui")
gui.Parent = modl
gui.Adornee = partb
gui.Size = UDim2.new(1, 0, 1, 0)
gui.StudsOffset = Vector3.new(0, 3, 0) 
	local frame = Instance.new("Frame")
	frame.Parent = gui
	frame.Size = UDim2.new(1, 0, 1, 0)
	frame.BackgroundTransparency = 1
local text = Instance.new("TextLabel") text.Parent = frame text.Size = UDim2.new(1, 0, 1, 0) text.BackgroundTransparency = 1 text.Text = "Health" ..health.Value 
text.FontSize = "Size14" 
local parbm = Instance.new("BlockMesh") 
parbm.Parent = partb
parbm.Bevel = 0.1 
local partc = Instance.new("Part") 
partc.Parent = modl 
partc.Anchored = true 
partc.BrickColor = Me.Character.Torso.BrickColor 
partc.formFactor = "Custom" 
partc.Size = Vector3.new(2.2, 0.25, 2.2) 
partc.CFrame = parta.CFrame + Vector3.new(0, 0.5, 0) 
local parcm = Instance.new("BlockMesh") 
parcm.Parent = partc
parcm.Bevel = 0.1 
local partd = Instance.new("Part") 
partd.Parent = modl 
partd.Anchored = true 
partd.BrickColor = Me.Character.Torso.BrickColor 
partd.formFactor = "Custom" 
partd.Size = Vector3.new(2.2, 0.25, 2.2) 
partd.CFrame = parta.CFrame + Vector3.new(0, 1.5, 0) 
local pardm = Instance.new("BlockMesh") 
pardm.Parent = partd
pardm.Bevel = 0.1 
	end 
	    if key == "y" and resc >= 250 then 
resc = resc - 250 
text2.Text = "Resources: " ..resc.. " " 
local modl = Instance.new("Model", workspace.Base) 
modl.Name = "War Factory - " ..Me.Name.. " " 
local hum = Instance.new("Humanoid", modl) 
hum.MaxHealth = 0 
hum.Health = 0 
local health = Instance.new("IntValue") 
health.Parent = modl 
health.Value = 100 
local pos = mouse.hit.p 
local parta = Instance.new("Part") 
parta.Parent = modl 
parta.Anchored = true 
parta.BrickColor = BrickColor.new("White") 
parta.formFactor = "Custom" 
parta.Name = "Torso" 
parta.Size = Vector3.new(5, 1, 5) 
parta.CFrame = CFrame.new(pos) 
local partm = Instance.new("BlockMesh") 
partm.Parent = parta
partm.Bevel = 0.1 
local partb = Instance.new("Part") 
partb.Parent = modl 
partb.Anchored = true 
partb.BrickColor = BrickColor.new("Dark stone grey") 
partb.formFactor = "Custom" 
partb.Name = "Head" 
partb.Size = Vector3.new(4.5, 5, 4.5) 
partb.CFrame = parta.CFrame + Vector3.new(0, 2.5, 0) 
local gui = Instance.new("BillboardGui")
gui.Parent = modl
gui.Adornee = partb
gui.Size = UDim2.new(1, 0, 1, 0)
gui.StudsOffset = Vector3.new(0, 3, 0) 
	local frame = Instance.new("Frame")
	frame.Parent = gui
	frame.Size = UDim2.new(1, 0, 1, 0)
	frame.BackgroundTransparency = 1
local text = Instance.new("TextLabel") text.Parent = frame text.Size = UDim2.new(1, 0, 1, 0) text.BackgroundTransparency = 1 text.Text = "Health" ..health.Value 
text.FontSize = "Size14" 
local parbm = Instance.new("BlockMesh") 
parbm.Parent = partb
parbm.Bevel = 0.1 
local partd = Instance.new("Part") 
partd.Parent = modl 
partd.Anchored = true 
partd.BrickColor = Me.Character.Torso.BrickColor 
partd.formFactor = "Custom" 
partd.Size = Vector3.new(4.7, 4, 4.7) 
partd.CFrame = parta.CFrame + Vector3.new(0, 2.5, 0) 
local pardm = Instance.new("BlockMesh") 
pardm.Parent = partd
pardm.Bevel = 0.1 
	end 
    end)
end

function onDesel(mouse)

end

bin.Selected:connect(onSelected)
bin.Deselected:connect(onDesel)

while true do 
resc = resc + count*10 
text2.Text = "Resources: " ..resc.. " " 
wait(2)
end 
