getglobal("game")
getfield(-1, "Workspace")
getglobal("Instance")
getfield(-1, "new")
pushstring("Sound")
pushvalue(-4)
pushstring("CPPMusic")
setfield(-2, "Name")
pcall(2, 1, 0)
pushstring("rbxassetid://787636293")
setfield(-2, "SoundId")
pushnumber(1)
setfield(-2, "Volume")
pushstring("true")
setfield(-2, "Playing")
pushvalue(-2)
emptystack()