color = "Reddish brown"
color2 = "black"
mod = Instance.new("Model", workspace.acb227) 
mod.Name = "House"
part = Instance.new("Part", mod)
part.BrickColor = BrickColor.new(color)
part.Material = "Wood"
part.Anchored = true
part.TopSurface = "Smooth"
part.BottomSurface = "Smooth"
part.Size = Vector3.new(30, 1, 30)
part.CFrame = CFrame.new(0, 0, 0)
part.Name = "Floor" 
part = Instance.new("Part", mod)
part.BrickColor = BrickColor.new(color)
part.Material = "Wood"
part.Anchored = true
part.TopSurface = "Smooth"
part.BottomSurface = "Smooth"
part.Size = Vector3.new(30, 15, 1)
part.CFrame = CFrame.new(0, 8, 14.5)
part.Name = "Walla" 
part = Instance.new("Part", mod)
part.BrickColor = BrickColor.new(color)
part.Material = "Wood"
part.Anchored = true
part.TopSurface = "Smooth"
part.BottomSurface = "Smooth"
part.Size = Vector3.new(30, 15, 1)
part.CFrame = CFrame.new(0, 8, -14.5)
part.Name = "Wallb" 
part = Instance.new("Part", mod)
part.BrickColor = BrickColor.new(color)
part.Material = "Wood"
part.Anchored = true
part.TopSurface = "Smooth"
part.BottomSurface = "Smooth"
part.Size = Vector3.new(1, 15, 30)
part.CFrame = CFrame.new(-14.5, 8, 0)
part.Name = "Wallc" 
part = Instance.new("Part", mod)
part.BrickColor = BrickColor.new(color)
part.Material = "Wood"
part.Anchored = true
part.TopSurface = "Smooth"
part.BottomSurface = "Smooth"
part.Size = Vector3.new(1, 15, 10)
part.CFrame = CFrame.new(14.5, 8, 10)
part.Name = "Walld" 
part = Instance.new("Part", mod)
part.BrickColor = BrickColor.new(color)
part.Material = "Wood"
part.Anchored = true
part.TopSurface = "Smooth"
part.BottomSurface = "Smooth"
part.Size = Vector3.new(1, 15, 10)
part.CFrame = CFrame.new(14.5, 8, -10)
part.Name = "Walle" 
part = Instance.new("Part", mod)
part.BrickColor = BrickColor.new(color)
part.Material = "Wood"
part.Anchored = true
part.TopSurface = "Smooth"
part.BottomSurface = "Smooth"
part.Size = Vector3.new(1, 15, 10)
part.CFrame = CFrame.new(14.5, 8, 0)
part.Name = "Door" 
part = Instance.new("Part", mod)
part.BrickColor = BrickColor.new(color2)
part.Material = "Wood"
part.Anchored = true
part.TopSurface = "Smooth"
part.BottomSurface = "Smooth"
part.Size = Vector3.new(30, 1, 15)
part.CFrame = CFrame.new(0, 16, 7.5)
part.Name = "Roofa" 
part = Instance.new("Part", mod)
part.BrickColor = BrickColor.new(color2)
part.Material = "Wood"
part.Anchored = true
part.TopSurface = "Smooth"
part.BottomSurface = "Smooth"
part.Size = Vector3.new(30, 1, 15)
part.CFrame = CFrame.new(0, 16, -7.5)
part.Name = "Roofb" 