local data={
	save=2,
	savedata={
		koins=40000,
		main={
			upgrades={dunk={max=9, current=0},
			defense={max=14, current=7},
			steal={max=12, current=0},
			jump={max=10, current=0},
			freethrow={max=11, current=0},
			shotcontest={max=13, current=0},
			["2pointer"]={max=8, current=0},
			["3pointer"]={max=7, current=0},
			handles={max=14, current=5},
			layup={max=12, current=0},
			postscorer={max=9, current=0},
			ballspeed={max=9, current=2},
			speed={max=11, current=3},
			passing={max=16, current=10},
			movingshot={max=13, current=0},
			strength={max=7, current=0}},
			park_onanimations={},
			rb7_celebrations={},
			jumpshots={"Starter Jumpshot 1", "Starter Jumpshot 2", "Starter Jumpshot 3"},
			prestige=1,
			pants={"Grey Joggers"},
			level=1,
			layups={"Starter Layup 1", "Starter Layup 2"},
			shoes={"RB Generics"},
			park="westlake",
			dunks={"Big Slam"},
			currentexp=0,
			hats={"Nothing"},
			customjumpshots={},
			park_celebrations={},
			position="PG",
			playstyle="Passer",
			skills={
				dunk=36,
				defense=50,
				steal=50,
				jump=45,
				freethrow=58,
				shotcontest=40,
				["2pointer"]=51,
				["3pointer"]=48,
				handles=52,
				layup=57,
				postscorer=35,
				ballspeed=57, 
				speed=58,
				passing=57,
				movingshot=58,
				strength=38
			},
			maxexp=100,
			shirts={"Plain White Shirt"}
		},
		appearance={
			dunk="698187843", park_onanimations={},
			rb7_celebrations={},
			hat2={meshid="", textureid="", name="None", pos={y=0, z=0}},
			layup={name="Starter Layup 1", idr="696678129", idl="696677707"},
			shirt="225684460",
			weight=190,
			pants="945117814",
			shoes={name="RB Generics", shoetype="MidShoe", idr="945506326", idl="945506326"},
			hat={meshid="", textureid="", name="None", pos={y=0, z=0}},
			skincolor="Cashmere",
			gender="Male",
			park_celebrations={},
			haircolor="Black",
			height=5,
			shothand="L",
			jumpshot={name="Starter Jumpshot 1", shot="697217666", jump="697208867"},
			hair={meshid="", pos={y=0, z=0},name="Bald",size={y=0, x=0, z=0}}
		},
		upgrading=1
	},
	maindata={
		friends={},
		name=game.Players.LocalPlayer.Name,
		park="",
		id=game.Players.LocalPlayer.userId,
		follow="Anyone",
		league=0,
		gym=0
	}
}

game.ReplicatedStorage.tp:FireServer(data)