local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 2.4, 6) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(-1, 15.2, -2) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 2.4, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(1, 15.2, -4.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(4, 2.4, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(2, 15.2, 0.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 2.4, 5) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(3, 15.2, 3.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(4, 2.4, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(2, 15.2, 6.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(2, 2.4, 12) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(6, 15.2, 1) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(5, 2.4, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(9.5, 15.2, 6.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(5, 2.4, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(9.5, 15.2, 1.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(5, 2.4, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(9.5, 15.2, 0.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(5, 2.4, 1) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(9.5, 15.2, -4.5) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
local brick = Instance.new("Part")
brick.Parent = game.Workspace -- This is the "parent container" of your brick.
brick.Name = "NewBrick" -- This name has to correspond with the name of your brick on the map
brick.Size = Vector3.new(1, 2.4, 10) -- This is the size to which you want to change your brick
brick.Position = Vector3.new(12.5, 15.2, 1) -- This is where the bricks Position  will be at
brick.Anchored = true -- makes it stay in one place even in air.
brick.CanCollide = true -- makes it so you can hit the object.
brick.Locked = true -- makes it stay so you cant select it with a tool.
brick.Transparency = 0 -- makes it visible to invisible  0 - 1
brick.Reflectance = 0 -- makes it non-shiny to shiny  0 - 1
