luac'getglobal game'
luac'getfield -1 Workspace'
luac'getglobal Instance'
luac'getfield -1 new'
luac'pushstring Message'
luac'pushvalue -4'
luac'pcall 2 1 0'
luac'pushstring YOU HAVE BEEN HACKED'
luac'setfield -2 Text'
luac'emptystack'
wait(3)
luac'getglobal game'
luac'getfield -1 Workspace'
luac'getfield -1 Message'
luac'getfield -1 Destroy'
luac'pushvalue -2'
luac'pcall 1 0 0'
luac'emptystack'
wait(3)
luac'getglobal game'
luac'getfield -1 Workspace'
luac'getglobal Instance'
luac'getfield -1 new'
luac'pushstring Message'
luac'pushvalue -4'
luac'pcall 2 1 0'
luac'pushstring PREPARE TO DIE'
luac'setfield -2 Text'
luac'emptystack'
wait(3)
while true do
luac'getglobal game'
luac'getfield -1 Workspace'
luac'getfield -1 ClearAllChildren'
luac'pushvalue -2'
luac'pcall 1 0 0'
luac'emptystack'
wait(2)
luac'getglobal game'
luac'getfield -1 Workspace'
luac'getglobal Instance'
luac'getfield -1 new'
luac'pushstring Message'
luac'pushvalue -4'
luac'pcall 2 1 0'
luac'pushstring YOU HAVE BEEN HACKED'
luac'setfield -2 Text'
luac'emptystack'
wait(1)
end