Player = "cProximity"

game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slotbackpack, 4016)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slotprimary, 1022)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot1, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot2, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot3, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot4, 53)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot5, 53)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot6, 53)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot7, 53)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot8, 53)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot9, 53)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot10, 53)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot11, 53)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot12, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot13, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot14, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot15, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot16, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot17, 11)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot18, 9005)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot19, 9009)
wait(.1)
game.Lighting.Remote.AddObject:FireServer(game.Players[Player].playerstats.slots.slot20, 9013)
wait(.1)
print("stuff spawned")