http://hastebin.com/raw/oxovegawet
http://hastebin.com/raw/vedaficote.lua
http://hastebin.com/raw/huhevivohe
http://hastebin.com/raw/inasisedak
http://hastebin.com/raw/julanaxeqe
https://paste.ee/r/xEfkv
http://hastebin.com/raw/iwabacodoz
http://hastebin.com/raw/xibojajuri
http://hastebin.com/raw/apudalurev
https://paste.ee/r/elXGa
http://pastebin.com/raw/vUPBELWk
http://hastebin.com/raw/itakosaxav
http://hastebin.com/raw/efolokowig