RedMack = game.Workspace.acb227
mod = Instance.new("Model") 
mod.Parent = RedMack 
mod.Name = "Teh Epic Scripter" 
wait() 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 2, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.01, 1.01, 1.01) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Right Leg"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Torso" 
rlegm3.Scale = Vector3.new(0.9, 1, 1.04) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Right Leg"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.3, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.04, 0.3, 1.04) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Right Leg"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Sphere" 
rlegm3.Scale = Vector3.new(0.5, 0.2, 0.5) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Right Leg"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, -1, 0.2)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.04, 0.4, 0.5) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Right Leg"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.45, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 2, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.01, 1.01, 1.01) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Right Arm"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.04, 0.55, 0.8) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Right Arm"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.25, -0.15)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.04, 0.3, 1.04) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Right Arm"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, -0.2, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Torso" 
rlegm3.Scale = Vector3.new(1.5, 0.8, 1.05) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Right Arm"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.9, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Sphere" 
rlegm3.Scale = Vector3.new(0.5, 0.2, 0.5) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Right Arm"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, -1, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 2, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.01, 1.01, 1.01) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Left Arm"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.04, 0.55, 0.8) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Left Arm"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.25, -0.15)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.04, 0.3, 1.04) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Left Arm"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, -0.2, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Torso" 
rlegm3.Scale = Vector3.new(1.5, 0.8, 1.05) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Left Arm"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.9, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Sphere" 
rlegm3.Scale = Vector3.new(0.5, 0.2, 0.5) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Left Arm"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, -1, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face2" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(0.85, 0.5, 0.5) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Head"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.05, -0.4)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face3" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(0.65, 0.4, 0.5) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Head"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, -0, -0.3)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 0 
rleg3.Size = Vector3.new(2, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Head" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 0 
rlegm3.Scale = Vector3.new(1.3, 1.3, 1.3) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Head"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 2, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.01, 1.01, 1.01) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Left Leg"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Torso" 
rlegm3.Scale = Vector3.new(0.9, 1, 1.04) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Left Leg"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.3, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.04, 0.3, 1.04) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Left Leg"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Sphere" 
rlegm3.Scale = Vector3.new(0.5, 0.2, 0.5) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Left Leg"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, -1, 0.2)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.04, 0.4, 0.5) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Left Leg"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.45, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(2, 2, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(1.01, 1.01, 1.01) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Torso"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0, 0)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

Antennae = Instance.new("Part") 
Antennae.formFactor = "Symmetric" 
Antennae.Size = Vector3.new(1, 1, 1) 
Antennae.BrickColor = BrickColor.new("White") 
Antennae.Name = "Face1" 
Antennae.Reflectance = 0 
Antennae.TopSurface = 0 
Antennae.CanCollide = false 
Antennae.Parent = mod 
Antennae.BottomSurface = 0 
AntennaeMesh = Instance.new("SpecialMesh") 
AntennaeMesh.MeshType = "Sphere" 
AntennaeMesh.Scale = Vector3.new(0.3, 0.3, 0.3) 
AntennaeMesh.Parent = Antennae 
AntennaeWeld = Instance.new("Weld") 
AntennaeWeld.Part0 = RedMack["Torso"] 
AntennaeWeld.Part1 = Antennae 
AntennaeWeld.Parent = Antennae 
AntennaeWeld.C0 = CFrame.new(-0.69, 2.85, 0)*CFrame.fromEulerAnglesXYZ(0, -4.715, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face1" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(0.1, 2, 0.1) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Torso"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(-0.69, 2.20, 0)*CFrame.fromEulerAnglesXYZ(0, -4.715, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(0.7, 1.1, 0.4) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Torso"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0.65, 0.45, -0.4)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(0.7, 1.1, 0.4) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Torso"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(-0.65, 0.45, -0.4)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = 6 
rlegm3.Scale = Vector3.new(0.6, 0.8, 0.4) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Torso"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.5, -0.4)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Torso" 
rlegm3.Scale = Vector3.new(1, 0.2, 0.7) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Torso"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0.65, 0.5, -0.6)*CFrame.fromEulerAnglesXYZ(4.715, 4.715, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Torso" 
rlegm3.Scale = Vector3.new(1, 0.2, 0.7) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Torso"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(-0.65, 0.5, -0.6)*CFrame.fromEulerAnglesXYZ(4.715, 4.715, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Reflectance = 0 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Torso" 
rlegm3.Scale = Vector3.new(1.5, 0.2, 1.5) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Torso"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, -0.3, -0.475)*CFrame.fromEulerAnglesXYZ(4.715, 0, 0) 

rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Amulet" 
rleg3.Reflectance = 0.4 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Sphere" 
rlegm3.Scale = Vector3.new(0.55, 0.7, 0.2) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Torso"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.5, -0.6)*CFrame.fromEulerAnglesXYZ(0, 0, 0) 
rleg3 = Instance.new("Part") 
rleg3.formFactor = 2 
rleg3.Size = Vector3.new(1, 1, 1) 
rleg3.BrickColor = BrickColor.new("White") 
rleg3.Name = "Face" 
rleg3.Transparency = 1 
rleg3.TopSurface = 0 
rleg3.CanCollide = false 
rleg3.Parent = mod 
rleg3.BottomSurface = 0 
rlegm3 = Instance.new("SpecialMesh") 
rlegm3.MeshType = "Torso" 
rlegm3.Scale = Vector3.new(1.5, 0.3, 2) 
rlegm3.Parent = rleg3 
rlegw3 = Instance.new("Weld") 
rlegw3.Part0 = RedMack["Torso"] 
rlegw3.Part1 = rleg3 
rlegw3.Parent = rleg3 
rlegw3.C0 = CFrame.new(0, 0.25, 0.58)*CFrame.fromEulerAnglesXYZ(14.145, 4.715, 0) 

hum = Instance.new("Humanoid") 
hum.Parent = mod 
hum.MaxHealth = 0 
wait() 
acb227.Torso.Transparency = 1 
acb227.Head.Transparency = 1 
acb227:findFirstChild("Left Leg").Transparency = 1 
acb227:findFirstChild("Left Arm").Transparency = 1 
acb227:findFirstChild("Right Leg").Transparency = 1 
acb227:findFirstChild("Right Arm").Transparency = 1 

User = game.Players.acb227 
if script.Parent.className ~= "HopperBin" then 
h = Instance.new("HopperBin") 
h.Parent = User.Backpack 
h.Name = "Sharp Lazer" 
script.Parent = User.Character 
end 

function move(mouse) 
local P = Instance.new("Part") 
local Place0 = CFrame.new(Antennae.CFrame.x,Antennae.CFrame.y,Antennae.CFrame.z) 
local Place1 = mouse.Hit.p 
local Place2 = mouse.Target 
P.formFactor = 0 
P.Size = Vector3.new(1,1,(Place0.p - Place1).magnitude) 
P.Name = "Laser" 
P.CFrame = CFrame.new((Place0.p + Place1)/2,Place0.p) 
P.Parent = RedMack 
P.BrickColor = BrickColor.new("Really black") 
P.Anchored = true 
P.CanCollide = false 
P.Locked = true 
P.BottomSurface = "Smooth" 
P.TopSurface = "Smooth" 
local mesh = Instance.new("SpecialMesh") 
mesh.Parent = P 
mesh.MeshType = "Brick" 
mesh.Name = "LengthMesh" 
mesh.Scale = Vector3.new(.1, .1, 1) 
local Handle = Instance.new("ArcHandles") 
Handle.Parent = Place2 
Handle.Adornee = Place2 
Handle.Color = BrickColor.new("Really red") 
local s = Instance.new("Smoke") 
s.Parent = Place2 
s.Color = Color3.new(0,0,0) 
for i = 1,20 do 
P.Transparency = i*0.05 
wait() 
end 
P:remove() 
Handle: Remove() 
s: Remove() 
if Place2.Anchored == false then 
Place2: BreakJoints() 
else 
Place2.Anchored = false 
Place2: BreakJoints() 
end 
end 

function selected(mouse) 
mouse.Button1Down:connect(function () move(mouse) end) 
end 

script.Parent.Selected:connect(selected)

--lego