--letters-- 
local P = Instance.new("Part", tard) 
P.BrickColor = BrickColor.new("White") 
P.Anchored = true 
P.formFactor = "Custom" 
P.Size = Vector3.new(0.2, 1, 0.2) 
P.CFrame = CFrame.new(11, 11, -3.5) 
Pm = Instance.new("BlockMesh", P) 
local P2 = Instance.new("Part", tard) 
P2.BrickColor = BrickColor.new("White") 
P2.Anchored = true 
P2.formFactor = "Custom" 
P2.Size = Vector3.new(0.2, 0.2, 0.5) 
P2.CFrame = CFrame.new(11, 11.4, -3.25) 
P2m = Instance.new("BlockMesh", P2) 
local P3 = Instance.new("Part", tard) 
P3.BrickColor = BrickColor.new("White") 
P3.Anchored = true 
P3.formFactor = "Custom" 
P3.Size = Vector3.new(0.2, 0.2, 0.5) 
P3.CFrame = CFrame.new(11, 11, -3.25) 
P3m = Instance.new("BlockMesh", P3) 
local P4 = Instance.new("Part", tard) 
P4.BrickColor = BrickColor.new("White") 
P4.Anchored = true 
P4.formFactor = "Custom" 
P4.Size = Vector3.new(0.2, 0.6, 0.2) 
P4.CFrame = CFrame.new(11, 11.2, -3) 
P4m = Instance.new("BlockMesh", P4) 
local O = Instance.new("Part", tard) 
O.BrickColor = BrickColor.new("White") 
O.Anchored = true 
O.formFactor = "Custom" 
O.Size = Vector3.new(0.2, 1, 0.2) 
O.CFrame = CFrame.new(11, 11, -2.6) 
Om = Instance.new("BlockMesh", O) 
local O2 = Instance.new("Part", tard) 
O2.BrickColor = BrickColor.new("White") 
O2.Anchored = true 
O2.formFactor = "Custom" 
O2.Size = Vector3.new(0.2, 0.2, 0.5) 
O2.CFrame = CFrame.new(11, 11.4, -2.4) 
O2m = Instance.new("BlockMesh", O2) 
local O3 = Instance.new("Part", tard) 
O3.BrickColor = BrickColor.new("White") 
O3.Anchored = true 
O3.formFactor = "Custom" 
O3.Size = Vector3.new(0.2, 0.2, 0.5) 
O3.CFrame = CFrame.new(11, 10.6, -2.4) 
O3m = Instance.new("BlockMesh", O3) 
local O4 = Instance.new("Part", tard) 
O4.BrickColor = BrickColor.new("White") 
O4.Anchored = true 
O4.formFactor = "Custom" 
O4.Size = Vector3.new(0.2, 1, 0.2) 
O4.CFrame = CFrame.new(11, 11, -2.2) 
O4m = Instance.new("BlockMesh", O4) 
local L = Instance.new("Part", tard) 
L.BrickColor = BrickColor.new("White") 
L.Anchored = true 
L.formFactor = "Custom" 
L.Size = Vector3.new(0.2, 1, 0.2) 
L.CFrame = CFrame.new(11, 11, -1.75) 
Lm = Instance.new("BlockMesh", L) 
local L2 = Instance.new("Part", tard) 
L2.BrickColor = BrickColor.new("White") 
L2.Anchored = true 
L2.formFactor = "Custom" 
L2.Size = Vector3.new(0.2, 0.2, 0.5) 
L2.CFrame = CFrame.new(11, 10.6, -1.5) 
L2m = Instance.new("BlockMesh", L2) 
local I = Instance.new("Part", tard) 
I.BrickColor = BrickColor.new("White") 
I.Anchored = true 
I.formFactor = "Custom" 
I.Size = Vector3.new(0.2, 1, 0.2) 
I.CFrame = CFrame.new(11, 11, -1) 
Im = Instance.new("BlockMesh", I) 
local C = Instance.new("Part", tard) 
C.BrickColor = BrickColor.new("White") 
C.Anchored = true 
C.formFactor = "Custom" 
C.Size = Vector3.new(0.2, 1, 0.2) 
C.CFrame = CFrame.new(11, 11, -0.6) 
Cm = Instance.new("BlockMesh", C) 
local C2 = Instance.new("Part", tard) 
C2.BrickColor = BrickColor.new("White") 
C2.Anchored = true 
C2.formFactor = "Custom" 
C2.Size = Vector3.new(0.2, 0.2, 0.5) 
C2.CFrame = CFrame.new(11, 11.4, -0.4) 
C2m = Instance.new("BlockMesh", C2) 
local C3 = Instance.new("Part", tard) 
C3.BrickColor = BrickColor.new("White") 
C3.Anchored = true 
C3.formFactor = "Custom" 
C3.Size = Vector3.new(0.2, 0.2, 0.5) 
C3.CFrame = CFrame.new(11, 10.6, -0.4) 
C3m = Instance.new("BlockMesh", C3) 
local E = Instance.new("Part", tard) 
E.BrickColor = BrickColor.new("White") 
E.Anchored = true 
E.formFactor = "Custom" 
E.Size = Vector3.new(0.2, 1, 0.2) 
E.CFrame = CFrame.new(11, 11, 0.15) 
Em = Instance.new("BlockMesh", E) 
local E2 = Instance.new("Part", tard) 
E2.BrickColor = BrickColor.new("White") 
E2.Anchored = true 
E2.formFactor = "Custom" 
E2.Size = Vector3.new(0.2, 0.2, 0.5) 
E2.CFrame = CFrame.new(11, 10.6, 0.3) 
E2m = Instance.new("BlockMesh", E2) 
local E3 = Instance.new("Part", tard) 
E3.BrickColor = BrickColor.new("White") 
E3.Anchored = true 
E3.formFactor = "Custom" 
E3.Size = Vector3.new(0.2, 0.2, 0.5) 
E3.CFrame = CFrame.new(11, 11, 0.3) 
E3m = Instance.new("BlockMesh", E3) 
local E4 = Instance.new("Part", tard) 
E4.BrickColor = BrickColor.new("White") 
E4.Anchored = true 
E4.formFactor = "Custom" 
E4.Size = Vector3.new(0.2, 0.2, 0.5) 
E4.CFrame = CFrame.new(11, 11.4, 0.3) 
E4m = Instance.new("BlockMesh", E4) 
local p = Instance.new("Part", tard) 
p.BrickColor = BrickColor.new("White") 
p.Anchored = true 
p.formFactor = "Custom" 
p.Size = Vector3.new(0.2, 1, 0.2) 
p.CFrame = CFrame.new(11, 11.2, 1) 
pm = Instance.new("BlockMesh", p) 
pm.Scale = Vector3.new(1, 0.5, 1) 
local p2 = Instance.new("Part", tard) 
p2.BrickColor = BrickColor.new("White") 
p2.Anchored = true 
p2.formFactor = "Custom" 
p2.Size = Vector3.new(0.2, 0.2, 0.5) 
p2.CFrame = CFrame.new(11, 11.4, 1.2) 
p2m = Instance.new("BlockMesh", p2) 
p2m.Scale = Vector3.new(1, 0.5, 0.5) 
local p3 = Instance.new("Part", tard) 
p3.BrickColor = BrickColor.new("White") 
p3.Anchored = true 
p3.formFactor = "Custom" 
p3.Size = Vector3.new(0.2, 0.2, 0.5) 
p3.CFrame = CFrame.new(11, 11.2, 1.2) 
p3m = Instance.new("BlockMesh", p3) 
p3m.Scale = Vector3.new(1, 0.5, 0.5) 
local p4 = Instance.new("Part", tard) 
p4.BrickColor = BrickColor.new("White") 
p4.Anchored = true 
p4.formFactor = "Custom" 
p4.Size = Vector3.new(0.2, 0.25, 0.2) 
p4.CFrame = CFrame.new(11, 11.3, 1.3) 
p4m = Instance.new("BlockMesh", p4) 
p4m.Scale = Vector3.new(1, 1, 0.5) 
local u = Instance.new("Part", tard) 
u.BrickColor = BrickColor.new("White") 
u.Anchored = true 
u.formFactor = "Custom" 
u.Size = Vector3.new(0.2, 0.5, 0.2) 
u.CFrame = CFrame.new(11, 11.2, 1.5) 
um = Instance.new("BlockMesh", u) 
um.Scale = Vector3.new(1, 1, 0.5) 
local u2 = Instance.new("Part", tard) 
u2.BrickColor = BrickColor.new("White") 
u2.Anchored = true 
u2.formFactor = "Custom" 
u2.Size = Vector3.new(0.2, 0.5, 0.2) 
u2.CFrame = CFrame.new(11, 11.2, 1.8) 
u2m = Instance.new("BlockMesh", u2) 
u2m.Scale = Vector3.new(1, 1, 0.5) 
local u3 = Instance.new("Part", tard) 
u3.BrickColor = BrickColor.new("White") 
u3.Anchored = true 
u3.formFactor = "Custom" 
u3.Size = Vector3.new(0.2, 0.2, 0.75) 
u3.CFrame = CFrame.new(11, 11, 1.65) 
u3m = Instance.new("BlockMesh", u3) 
u3m.Scale = Vector3.new(1, 0.5, 0.5) 