--Trailer Script by dms xd
DoorColor = "Cocoa" --door colorxd
TrailerColor = "Maroon" --General Trailer Color
CouchColor = "Smoky grey"
FridgeOvenColor = "Medium stone grey"
FridgeOvenColor2 = "Really black"


P1 = Instance.new("Part")
P1.Size = Vector3.new(0.31, 2.98, 2)
P1.Parent = game.Workspace
P1.Anchored = true
P1.CanCollide = true
P1.TopSurface = "SmoothNoOutlines"
P1.BottomSurface = "SmoothNoOutlines"
P1.FrontSurface = "SmoothNoOutlines"
P1.LeftSurface = "SmoothNoOutlines"
P1.RightSurface = "SmoothNoOutlines"
P1.BrickColor = BrickColor.new("Really black")
P1.Position = Vector3.new(21.505, 1.49, -13.77) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,3,0)
P2 = Instance.new("Part")
P2.Parent = game.Workspace
P2.Position = Vector3.new(6.28, 3.51, -13.19) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,3,0)
P2.Anchored = true
P2.CanCollide = true
P2.TopSurface = "SmoothNoOutlines"
P2.BottomSurface = "SmoothNoOutlines"
P2.FrontSurface = "SmoothNoOutlines"
P2.LeftSurface = "SmoothNoOutlines"
P2.RightSurface = "SmoothNoOutlines"
P2.BrickColor = BrickColor.new("Black")
P2.Size = Vector3.new(31.34, 1, 12.88)
P3 = Instance.new("Part")
P3.Size = Vector3.new(4, 3, 3.2)
P3.Parent = game.Workspace
P3.Anchored = true
P3.CanCollide = true
P3.TopSurface = "SmoothNoOutlines"
P3.BottomSurface = "SmoothNoOutlines"
P3.FrontSurface = "SmoothNoOutlines"
P3.LeftSurface = "SmoothNoOutlines"
P3.RightSurface = "SmoothNoOutlines"
P3.BrickColor = BrickColor.new("Really black")
P3.Shape = "Cylinder"
P3.Rotation = Vector3.new(0,-90,0)
P3.Position = Vector3.new(-3, 1.51, -8.8) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,3,0)
P4 = Instance.new("Part")
P4.Size = Vector3.new(4, 3, 3.2)
P4.Parent = game.Workspace
P4.Anchored = true
P4.CanCollide = true
P4.TopSurface = "SmoothNoOutlines"
P4.BottomSurface = "SmoothNoOutlines"
P4.FrontSurface = "SmoothNoOutlines"
P4.LeftSurface = "SmoothNoOutlines"
P4.RightSurface = "SmoothNoOutlines"
P4.BrickColor = BrickColor.new("Really black")
P4.Shape = "Cylinder"
P4.Rotation = Vector3.new(0,-90,0)
P4.Position = Vector3.new(-3, 1.51, -17.6) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,3,0)
P5 = Instance.new("Part")
P5.Size = Vector3.new(0.75, 9.5, 12.88)
P5.Parent = game.Workspace
P5.Anchored = true
P5.CanCollide = true
P5.TopSurface = "SmoothNoOutlines"
P5.BottomSurface = "SmoothNoOutlines"
P5.FrontSurface = "SmoothNoOutlines"
P5.LeftSurface = "SmoothNoOutlines"
P5.RightSurface = "SmoothNoOutlines"
P5.BrickColor = BrickColor.new(TrailerColor)
P5.Rotation = Vector3.new(0,0,0)
P5.Position = Vector3.new(21.575, 8.7, -13.19) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,3,0)
P6 = Instance.new("Part")
P6.Size = Vector3.new(2.73, 9.38, 0.61)
P6.Parent = game.Workspace
P6.Anchored = true
P6.CanCollide = true
P6.TopSurface = "SmoothNoOutlines"
P6.BottomSurface = "SmoothNoOutlines"
P6.FrontSurface = "SmoothNoOutlines"
P6.LeftSurface = "SmoothNoOutlines"
P6.RightSurface = "SmoothNoOutlines"
P6.BrickColor = BrickColor.new(TrailerColor)
P6.Rotation = Vector3.new(0,0,0)
P6.Position = Vector3.new(19.83, 8.7, -7.055) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,3,0)
P7 = Instance.new("Part")
P7.Size = Vector3.new(21, 9.38, 0.61)
P7.Parent = game.Workspace
P7.Anchored = true
P7.CanCollide = true
P7.TopSurface = "SmoothNoOutlines"
P7.BottomSurface = "SmoothNoOutlines"
P7.FrontSurface = "SmoothNoOutlines"
P7.LeftSurface = "SmoothNoOutlines"
P7.RightSurface = "SmoothNoOutlines"
P7.BrickColor = BrickColor.new(TrailerColor)
P7.Rotation = Vector3.new(0,0,0)
P7.Position = Vector3.new(1.93, 8.7, -7.055) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
P8 = Instance.new("Part")
P8.Size = Vector3.new(0.75, 9.38, 12.88)
P8.Parent = game.Workspace
P8.Anchored = true
P8.CanCollide = true
P8.TopSurface = "SmoothNoOutlines"
P8.BottomSurface = "SmoothNoOutlines"
P8.FrontSurface = "SmoothNoOutlines"
P8.LeftSurface = "SmoothNoOutlines"
P8.RightSurface = "SmoothNoOutlines"
P8.BrickColor = BrickColor.new(TrailerColor)
P8.Rotation = Vector3.new(0,0,0)
P8.Position = Vector3.new(-9.015, 8.7, -13.19) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
P9 = Instance.new("Part")
P9.Size = Vector3.new(29.63, 9.38, 0.61)
P9.Parent = game.Workspace
P9.Anchored = true
P9.CanCollide = true
P9.TopSurface = "SmoothNoOutlines"
P9.BottomSurface = "SmoothNoOutlines"
P9.FrontSurface = "SmoothNoOutlines"
P9.LeftSurface = "SmoothNoOutlines"
P9.RightSurface = "SmoothNoOutlines"
P9.BrickColor = BrickColor.new(TrailerColor)
P9.Rotation = Vector3.new(0,0,0)
P9.Position = Vector3.new(6.245, 8.7, -19.285) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
P10 = Instance.new("Part")
P10.Size = Vector3.new(31.34, 1, 12.88)
P10.Parent = game.Workspace
P10.Anchored = true
P10.CanCollide = true
P10.TopSurface = "SmoothNoOutlines"
P10.BottomSurface = "SmoothNoOutlines"
P10.FrontSurface = "SmoothNoOutlines"
P10.LeftSurface = "SmoothNoOutlines"
P10.RightSurface = "SmoothNoOutlines"
P10.BrickColor = BrickColor.new("Black")
P10.Rotation = Vector3.new(0,0,0)
P10.Position = Vector3.new(6.28, 13.89, -13.19) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.97,0)
P11 = Instance.new("Part")
P11.Size = Vector3.new(14.78, 3.65, 12.88)
P11.Parent = game.Workspace
P11.Anchored = true
P11.CanCollide = true
P11.TopSurface = "SmoothNoOutlines"
P11.BottomSurface = "SmoothNoOutlines"
P11.FrontSurface = "SmoothNoOutlines"
P11.LeftSurface = "SmoothNoOutlines"
P11.RightSurface = "SmoothNoOutlines"
P11.BrickColor = BrickColor.new(TrailerColor)
P11.Rotation = Vector3.new(0,0,0)
P11.Position = Vector3.new(-2, 16.215, -13.19) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.97,0)
P12 = Instance.new("Part")
P12.Size = Vector3.new(5.87, 9.38, 0.61)
P12.Parent = game.Workspace
P12.Anchored = true
P12.CanCollide = false
P12.TopSurface = "SmoothNoOutlines"
P12.BottomSurface = "SmoothNoOutlines"
P12.FrontSurface = "SmoothNoOutlines"
P12.LeftSurface = "SmoothNoOutlines"
P12.RightSurface = "SmoothNoOutlines"
P12.BrickColor = BrickColor.new(DoorColor)
P12.Rotation = Vector3.new(0,0,0)
P12.Position = Vector3.new(15.44, 8.7, -7.055) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
C1 = Instance.new("Part")
C1.Size = Vector3.new(11.09, 1.84, 3.05)
C1.Parent = game.Workspace
C1.Anchored = true
C1.CanCollide = true
C1.TopSurface = "SmoothNoOutlines"
C1.BottomSurface = "SmoothNoOutlines"
C1.FrontSurface = "SmoothNoOutlines"
C1.LeftSurface = "SmoothNoOutlines"
C1.RightSurface = "SmoothNoOutlines"
C1.BrickColor = BrickColor.new(CouchColor)
C1.Rotation = Vector3.new(0,0,0)
C1.Position = Vector3.new(13.755, 4.93, -17.075) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
C2 = Instance.new("Part")
C2.Size = Vector3.new(9.48, 3.66, 0.65)
C2.Parent = game.Workspace
C2.Anchored = true
C2.CanCollide = true
C2.TopSurface = "SmoothNoOutlines"
C2.BottomSurface = "SmoothNoOutlines"
C2.FrontSurface = "SmoothNoOutlines"
C2.LeftSurface = "SmoothNoOutlines"
C2.RightSurface = "SmoothNoOutlines"
C2.BrickColor = BrickColor.new(CouchColor)
C2.Rotation = Vector3.new(0,0,0)
C2.Position = Vector3.new(13.74, 7.68, -18.275) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
C3 = Instance.new("Part")
C3.Size = Vector3.new(0.78, 1.84, 2.93)
C3.Parent = game.Workspace
C3.Anchored = true
C3.CanCollide = true
C3.TopSurface = "SmoothNoOutlines"
C3.BottomSurface = "SmoothNoOutlines"
C3.FrontSurface = "SmoothNoOutlines"
C3.LeftSurface = "SmoothNoOutlines"
C3.RightSurface = "SmoothNoOutlines"
C3.BrickColor = BrickColor.new(CouchColor)
C3.Rotation = Vector3.new(0,0,0)
C3.Position = Vector3.new(8.6, 6.77, -17) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
C4 = Instance.new("Part")
C4.Size = Vector3.new(0.78, 1.84, 2.77)
C4.Parent = game.Workspace
C4.Anchored = true
C4.CanCollide = true
C4.TopSurface = "SmoothNoOutlines"
C4.BottomSurface = "SmoothNoOutlines"
C4.FrontSurface = "SmoothNoOutlines"
C4.LeftSurface = "SmoothNoOutlines"
C4.RightSurface = "SmoothNoOutlines"
C4.BrickColor = BrickColor.new(CouchColor)
C4.Rotation = Vector3.new(0,0,0)
C4.Position = Vector3.new(18.9, 6.77, -17.1) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
C5 = Instance.new("Seat")
C5.Size = Vector3.new(4, 0.2, 1.7)
C5.Parent = game.Workspace
C5.Anchored = true
C5.CanCollide = true
C5.Transparency = 1
C5.TopSurface = "SmoothNoOutlines"
C5.BottomSurface = "SmoothNoOutlines"
C5.FrontSurface = "SmoothNoOutlines"
C5.LeftSurface = "SmoothNoOutlines"
C5.RightSurface = "SmoothNoOutlines"
C5.BrickColor = BrickColor.new(CouchColor)
C5.Rotation = Vector3.new(-180, 0, -180)
C5.Position = Vector3.new(11.2, 5.95, -16.65) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
C6 = Instance.new("Seat")
C6.Size = Vector3.new(4, 0.2, 1.7)
C6.Parent = game.Workspace
C6.Anchored = true
C6.CanCollide = true
C6.Transparency = 1
C6.TopSurface = "SmoothNoOutlines"
C6.BottomSurface = "SmoothNoOutlines"
C6.FrontSurface = "SmoothNoOutlines"
C6.LeftSurface = "SmoothNoOutlines"
C6.RightSurface = "SmoothNoOutlines"
C6.BrickColor = BrickColor.new(CouchColor)
C6.Rotation = Vector3.new(-180, 0, -180)
C6.Position = Vector3.new(16.16, 5.95, -16.65) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
F1 = Instance.new("Part")
F1.Size = Vector3.new(3.45, 8.16, 3.5)
F1.Parent = game.Workspace
F1.Anchored = true
F1.CanCollide = true
F1.TopSurface = "SmoothNoOutlines"
F1.BottomSurface = "SmoothNoOutlines"
F1.FrontSurface = "SmoothNoOutlines"
F1.LeftSurface = "SmoothNoOutlines"
F1.RightSurface = "SmoothNoOutlines"
F1.BrickColor = BrickColor.new(FridgeOvenColor)
F1.Position = Vector3.new(-6.244, 8.09, -9.51) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
F2 = Instance.new("Part")
F2.Size = Vector3.new(0.2, 2.42, 0.2)
F2.Parent = game.Workspace
F2.Anchored = true
F2.CanCollide = true
F2.TopSurface = "SmoothNoOutlines"
F2.BottomSurface = "SmoothNoOutlines"
F2.FrontSurface = "SmoothNoOutlines"
F2.LeftSurface = "SmoothNoOutlines"
F2.RightSurface = "SmoothNoOutlines"
F2.BrickColor = BrickColor.new(FridgeOvenColor2)
F2.Position = Vector3.new(-4.34, 5.73, -10.8) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
F3 = Instance.new("Part")
F3.Size = Vector3.new(0.2, 4.2, 0.2)
F3.Parent = game.Workspace
F3.Anchored = true
F3.CanCollide = true
F3.TopSurface = "SmoothNoOutlines"
F3.BottomSurface = "SmoothNoOutlines"
F3.FrontSurface = "SmoothNoOutlines"
F3.LeftSurface = "SmoothNoOutlines"
F3.RightSurface = "SmoothNoOutlines"
F3.BrickColor = BrickColor.new(FridgeOvenColor2)
F3.Position = Vector3.new(-4.35, 9.74, -10.8) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
O1 = Instance.new("Part")
O1.Size = Vector3.new(4.2, 3.52, 4.94)
O1.Parent = game.Workspace
O1.Anchored = true
O1.CanCollide = true
O1.TopSurface = "SmoothNoOutlines"
O1.BottomSurface = "SmoothNoOutlines"
O1.FrontSurface = "SmoothNoOutlines"
O1.LeftSurface = "SmoothNoOutlines"
O1.RightSurface = "SmoothNoOutlines"
O1.BrickColor = BrickColor.new(FridgeOvenColor)
O1.Position = Vector3.new(-6.35, 5.77, -14.98) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
O2 = Instance.new("Part")
O2.Size = Vector3.new(1.15, 2.61, 4.94)
O2.Parent = game.Workspace
O2.Anchored = true
O2.CanCollide = true
O2.TopSurface = "SmoothNoOutlines"
O2.BottomSurface = "SmoothNoOutlines"
O2.FrontSurface = "SmoothNoOutlines"
O2.LeftSurface = "SmoothNoOutlines"
O2.RightSurface = "SmoothNoOutlines"
O2.BrickColor = BrickColor.new(FridgeOvenColor)
O2.Position = Vector3.new(-7.875, 8.835, -14.96) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
O3 = Instance.new("Part")
O3.Size = Vector3.new(0.2, 1.16, 2.23)
O3.Parent = game.Workspace
O3.Anchored = true
O3.CanCollide = true
O3.TopSurface = "SmoothNoOutlines"
O3.BottomSurface = "SmoothNoOutlines"
O3.FrontSurface = "SmoothNoOutlines"
O3.LeftSurface = "SmoothNoOutlines"
O3.RightSurface = "SmoothNoOutlines"
O3.BrickColor = BrickColor.new(FridgeOvenColor2)
O3.Position = Vector3.new(-7.16, 9.42, -14.965) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
CR1 = Instance.new("Part")
CR1.Size = Vector3.new(8.54, 3.52, 2.45)
CR1.Parent = game.Workspace
CR1.Anchored = true
CR1.CanCollide = true
CR1.TopSurface = "SmoothNoOutlines"
CR1.BottomSurface = "SmoothNoOutlines"
CR1.FrontSurface = "SmoothNoOutlines"
CR1.LeftSurface = "SmoothNoOutlines"
CR1.RightSurface = "SmoothNoOutlines"
CR1.BrickColor = BrickColor.new(FridgeOvenColor)
CR1.Position = Vector3.new(2.15, 5.77, -17.335) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)
CR2 = Instance.new("Part")
CR2.Size = Vector3.new(8.54, 0.2, 2.66)
CR2.Parent = game.Workspace
CR2.Anchored = true
CR2.CanCollide = true
CR2.TopSurface = "SmoothNoOutlines"
CR2.BottomSurface = "SmoothNoOutlines"
CR2.FrontSurface = "SmoothNoOutlines"
CR2.LeftSurface = "SmoothNoOutlines"
CR2.RightSurface = "SmoothNoOutlines"
CR2.BrickColor = BrickColor.new(FridgeOvenColor2)
CR2.Position = Vector3.new(2.15, 7.63, -17.335) + game.Players.LocalPlayer.Character.Torso.Position - Vector3.new(0,2.98,0)